//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartOfSection">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://taf-jsg.info/schemes}LocationIdent">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element ref="{http://taf-jsg.info/schemes}BookedLocationDateTime" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EndOfSection">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://taf-jsg.info/schemes}LocationIdent">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element ref="{http://taf-jsg.info/schemes}BookedLocationDateTime" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}OperationalTrainNumber" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}PlannedCalendar"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}NetworkSpecificParameter" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startOfSection",
    "endOfSection",
    "operationalTrainNumber",
    "plannedCalendar",
    "networkSpecificParameter"
})
@XmlRootElement(name = "AffectedSection")
public class AffectedSection {

    @XmlElement(name = "StartOfSection", required = true)
    protected AffectedSection.StartOfSection startOfSection;
    @XmlElement(name = "EndOfSection", required = true)
    protected AffectedSection.EndOfSection endOfSection;
    @XmlElement(name = "OperationalTrainNumber")
    protected String operationalTrainNumber;
    @XmlElement(name = "PlannedCalendar", required = true)
    protected PlannedCalendar plannedCalendar;
    @XmlElement(name = "NetworkSpecificParameter")
    protected List<NetworkSpecificParameter> networkSpecificParameter;

    /**
     * Gets the value of the startOfSection property.
     * 
     * @return
     *     possible object is
     *     {@link AffectedSection.StartOfSection }
     *     
     */
    public AffectedSection.StartOfSection getStartOfSection() {
        return startOfSection;
    }

    /**
     * Sets the value of the startOfSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffectedSection.StartOfSection }
     *     
     */
    public void setStartOfSection(AffectedSection.StartOfSection value) {
        this.startOfSection = value;
    }

    /**
     * Gets the value of the endOfSection property.
     * 
     * @return
     *     possible object is
     *     {@link AffectedSection.EndOfSection }
     *     
     */
    public AffectedSection.EndOfSection getEndOfSection() {
        return endOfSection;
    }

    /**
     * Sets the value of the endOfSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffectedSection.EndOfSection }
     *     
     */
    public void setEndOfSection(AffectedSection.EndOfSection value) {
        this.endOfSection = value;
    }

    /**
     * Gets the value of the operationalTrainNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalTrainNumber() {
        return operationalTrainNumber;
    }

    /**
     * Sets the value of the operationalTrainNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalTrainNumber(String value) {
        this.operationalTrainNumber = value;
    }

    /**
     * Gets the value of the plannedCalendar property.
     * 
     * @return
     *     possible object is
     *     {@link PlannedCalendar }
     *     
     */
    public PlannedCalendar getPlannedCalendar() {
        return plannedCalendar;
    }

    /**
     * Sets the value of the plannedCalendar property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlannedCalendar }
     *     
     */
    public void setPlannedCalendar(PlannedCalendar value) {
        this.plannedCalendar = value;
    }

    /**
     * Gets the value of the networkSpecificParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the networkSpecificParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNetworkSpecificParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NetworkSpecificParameter }
     * 
     * 
     */
    public List<NetworkSpecificParameter> getNetworkSpecificParameter() {
        if (networkSpecificParameter == null) {
            networkSpecificParameter = new ArrayList<NetworkSpecificParameter>();
        }
        return this.networkSpecificParameter;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://taf-jsg.info/schemes}LocationIdent">
     *       &lt;sequence minOccurs="0">
     *         &lt;element ref="{http://taf-jsg.info/schemes}BookedLocationDateTime" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bookedLocationDateTime"
    })
    public static class EndOfSection
        extends LocationIdent
    {

        @XmlElement(name = "BookedLocationDateTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar bookedLocationDateTime;

        /**
         * Gets the value of the bookedLocationDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getBookedLocationDateTime() {
            return bookedLocationDateTime;
        }

        /**
         * Sets the value of the bookedLocationDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setBookedLocationDateTime(XMLGregorianCalendar value) {
            this.bookedLocationDateTime = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://taf-jsg.info/schemes}LocationIdent">
     *       &lt;sequence minOccurs="0">
     *         &lt;element ref="{http://taf-jsg.info/schemes}BookedLocationDateTime" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bookedLocationDateTime"
    })
    public static class StartOfSection
        extends LocationIdent
    {

        @XmlElement(name = "BookedLocationDateTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar bookedLocationDateTime;

        /**
         * Gets the value of the bookedLocationDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getBookedLocationDateTime() {
            return bookedLocationDateTime;
        }

        /**
         * Sets the value of the bookedLocationDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setBookedLocationDateTime(XMLGregorianCalendar value) {
            this.bookedLocationDateTime = value;
        }

    }

}
