//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageHeader"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}CommitmentETA"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ActualETA"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberFreight"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeader",
    "commitmentETA",
    "actualETA",
    "wagonNumberFreight"
})
@XmlRootElement(name = "AlertMessage")
public class AlertMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeader messageHeader;
    @XmlElement(name = "CommitmentETA", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar commitmentETA;
    @XmlElement(name = "ActualETA", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actualETA;
    @XmlElement(name = "WagonNumberFreight", required = true)
    protected String wagonNumberFreight;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the commitmentETA property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCommitmentETA() {
        return commitmentETA;
    }

    /**
     * Sets the value of the commitmentETA property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCommitmentETA(XMLGregorianCalendar value) {
        this.commitmentETA = value;
    }

    /**
     * Gets the value of the actualETA property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualETA() {
        return actualETA;
    }

    /**
     * Sets the value of the actualETA property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualETA(XMLGregorianCalendar value) {
        this.actualETA = value;
    }

    /**
     * Gets the value of the wagonNumberFreight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWagonNumberFreight() {
        return wagonNumberFreight;
    }

    /**
     * Sets the value of the wagonNumberFreight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWagonNumberFreight(String value) {
        this.wagonNumberFreight = value;
    }

}
