//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageHeader"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageStatus"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainOperationalIdentification" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}OperationalTrainNumberIdentifier"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ReferenceOTN" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LocationPlannedTrack" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LocationActualTrack"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}BookedLocationDateTime" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainLocationStatus" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}InterruptionReason" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}InterruptionDescription" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TransferPoint" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TransfereeIM" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeader",
    "messageStatus",
    "trainOperationalIdentification",
    "operationalTrainNumberIdentifier",
    "referenceOTN",
    "locationPlannedTrack",
    "locationActualTrack",
    "bookedLocationDateTime",
    "trainLocationStatus",
    "interruptionReason",
    "interruptionDescription",
    "transferPoint",
    "transfereeIM"
})
@XmlRootElement(name = "ChangeofTrackMessage")
public class ChangeofTrackMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeader messageHeader;
    @XmlElement(name = "MessageStatus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String messageStatus;
    @XmlElement(name = "TrainOperationalIdentification")
    protected TrainOperationalIdentification trainOperationalIdentification;
    @XmlElement(name = "OperationalTrainNumberIdentifier", required = true)
    protected OperationalTrainNumberIdentifier operationalTrainNumberIdentifier;
    @XmlElement(name = "ReferenceOTN")
    protected ReferenceOTN referenceOTN;
    @XmlElement(name = "LocationPlannedTrack")
    protected LocationIdent locationPlannedTrack;
    @XmlElement(name = "LocationActualTrack", required = true)
    protected LocationIdent locationActualTrack;
    @XmlElement(name = "BookedLocationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bookedLocationDateTime;
    @XmlElement(name = "TrainLocationStatus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String trainLocationStatus;
    @XmlElement(name = "InterruptionReason")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String interruptionReason;
    @XmlElement(name = "InterruptionDescription")
    protected List<String> interruptionDescription;
    @XmlElement(name = "TransferPoint")
    protected LocationIdent transferPoint;
    @XmlElement(name = "TransfereeIM")
    protected Integer transfereeIM;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Assigned by the Sender 1=Creation,
     * 							2=Modification, 3=deletion
     * 						
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageStatus() {
        return messageStatus;
    }

    /**
     * Sets the value of the messageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageStatus(String value) {
        this.messageStatus = value;
    }

    /**
     * Gets the value of the trainOperationalIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link TrainOperationalIdentification }
     *     
     */
    public TrainOperationalIdentification getTrainOperationalIdentification() {
        return trainOperationalIdentification;
    }

    /**
     * Sets the value of the trainOperationalIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainOperationalIdentification }
     *     
     */
    public void setTrainOperationalIdentification(TrainOperationalIdentification value) {
        this.trainOperationalIdentification = value;
    }

    /**
     * Gets the value of the operationalTrainNumberIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalTrainNumberIdentifier }
     *     
     */
    public OperationalTrainNumberIdentifier getOperationalTrainNumberIdentifier() {
        return operationalTrainNumberIdentifier;
    }

    /**
     * Sets the value of the operationalTrainNumberIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalTrainNumberIdentifier }
     *     
     */
    public void setOperationalTrainNumberIdentifier(OperationalTrainNumberIdentifier value) {
        this.operationalTrainNumberIdentifier = value;
    }

    /**
     * Gets the value of the referenceOTN property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceOTN }
     *     
     */
    public ReferenceOTN getReferenceOTN() {
        return referenceOTN;
    }

    /**
     * Sets the value of the referenceOTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceOTN }
     *     
     */
    public void setReferenceOTN(ReferenceOTN value) {
        this.referenceOTN = value;
    }

    /**
     * Gets the value of the locationPlannedTrack property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getLocationPlannedTrack() {
        return locationPlannedTrack;
    }

    /**
     * Sets the value of the locationPlannedTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setLocationPlannedTrack(LocationIdent value) {
        this.locationPlannedTrack = value;
    }

    /**
     * Gets the value of the locationActualTrack property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getLocationActualTrack() {
        return locationActualTrack;
    }

    /**
     * Sets the value of the locationActualTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setLocationActualTrack(LocationIdent value) {
        this.locationActualTrack = value;
    }

    /**
     * Scheduled Date and Time of a train at a speciied
     * 							location as defined in the path contract
     * 						
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookedLocationDateTime() {
        return bookedLocationDateTime;
    }

    /**
     * Sets the value of the bookedLocationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookedLocationDateTime(XMLGregorianCalendar value) {
        this.bookedLocationDateTime = value;
    }

    /**
     * Gets the value of the trainLocationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainLocationStatus() {
        return trainLocationStatus;
    }

    /**
     * Sets the value of the trainLocationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainLocationStatus(String value) {
        this.trainLocationStatus = value;
    }

    /**
     * Gets the value of the interruptionReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterruptionReason() {
        return interruptionReason;
    }

    /**
     * Sets the value of the interruptionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterruptionReason(String value) {
        this.interruptionReason = value;
    }

    /**
     * Gets the value of the interruptionDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interruptionDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterruptionDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInterruptionDescription() {
        if (interruptionDescription == null) {
            interruptionDescription = new ArrayList<String>();
        }
        return this.interruptionDescription;
    }

    /**
     * Transfer point or station of destination in the
     * 							considered network where the Reference Train Numbers refers to
     * 						
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getTransferPoint() {
        return transferPoint;
    }

    /**
     * Sets the value of the transferPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setTransferPoint(LocationIdent value) {
        this.transferPoint = value;
    }

    /**
     * Gets the value of the transfereeIM property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransfereeIM() {
        return transfereeIM;
    }

    /**
     * Sets the value of the transfereeIM property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransfereeIM(Integer value) {
        this.transfereeIM = value;
    }

}
