//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RetailServiceID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="6"/>
 *               &lt;pattern value=""/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CommercialNumberOfVehicle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}CommercialTrafficType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "retailServiceID",
    "commercialNumberOfVehicle",
    "commercialTrafficType"
})
@XmlRootElement(name = "CoachOrTrainsetCommercialData")
public class CoachOrTrainsetCommercialData {

    @XmlElement(name = "RetailServiceID", required = true)
    protected String retailServiceID;
    @XmlElement(name = "CommercialNumberOfVehicle")
    protected String commercialNumberOfVehicle;
    @XmlElement(name = "CommercialTrafficType")
    protected BigInteger commercialTrafficType;

    /**
     * Gets the value of the retailServiceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRetailServiceID() {
        return retailServiceID;
    }

    /**
     * Sets the value of the retailServiceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRetailServiceID(String value) {
        this.retailServiceID = value;
    }

    /**
     * Gets the value of the commercialNumberOfVehicle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialNumberOfVehicle() {
        return commercialNumberOfVehicle;
    }

    /**
     * Sets the value of the commercialNumberOfVehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialNumberOfVehicle(String value) {
        this.commercialNumberOfVehicle = value;
    }

    /**
     * Gets the value of the commercialTrafficType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCommercialTrafficType() {
        return commercialTrafficType;
    }

    /**
     * Sets the value of the commercialTrafficType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCommercialTrafficType(BigInteger value) {
        this.commercialTrafficType = value;
    }

}
