//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}HandBrakeType"/>
 *         &lt;element name="HandBrakedWeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="4"/>
 *               &lt;fractionDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ParkingBrakeForce" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="5"/>
 *               &lt;fractionDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "handBrakeType",
    "handBrakedWeight",
    "parkingBrakeForce"
})
@XmlRootElement(name = "HandBrake")
public class HandBrake {

    @XmlElement(name = "HandBrakeType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String handBrakeType;
    @XmlElement(name = "HandBrakedWeight")
    protected BigDecimal handBrakedWeight;
    @XmlElement(name = "ParkingBrakeForce")
    protected BigDecimal parkingBrakeForce;

    /**
     * Gets the value of the handBrakeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandBrakeType() {
        return handBrakeType;
    }

    /**
     * Sets the value of the handBrakeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandBrakeType(String value) {
        this.handBrakeType = value;
    }

    /**
     * Gets the value of the handBrakedWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHandBrakedWeight() {
        return handBrakedWeight;
    }

    /**
     * Sets the value of the handBrakedWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHandBrakedWeight(BigDecimal value) {
        this.handBrakedWeight = value;
    }

    /**
     * Gets the value of the parkingBrakeForce property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getParkingBrakeForce() {
        return parkingBrakeForce;
    }

    /**
     * Sets the value of the parkingBrakeForce property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setParkingBrakeForce(BigDecimal value) {
        this.parkingBrakeForce = value;
    }

}
