//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}PlannedTransportIdentifiers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}RelatedPlannedTransportIdentifiers" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "plannedTransportIdentifiers",
    "relatedPlannedTransportIdentifiers"
})
@XmlRootElement(name = "Identifiers")
public class Identifiers {

    @XmlElement(name = "PlannedTransportIdentifiers")
    protected List<CompositIdentifierPlannedType> plannedTransportIdentifiers;
    @XmlElement(name = "RelatedPlannedTransportIdentifiers")
    protected List<CompositIdentifierPlannedType> relatedPlannedTransportIdentifiers;

    /**
     * Gets the value of the plannedTransportIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedTransportIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedTransportIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompositIdentifierPlannedType }
     * 
     * 
     */
    public List<CompositIdentifierPlannedType> getPlannedTransportIdentifiers() {
        if (plannedTransportIdentifiers == null) {
            plannedTransportIdentifiers = new ArrayList<CompositIdentifierPlannedType>();
        }
        return this.plannedTransportIdentifiers;
    }

    /**
     * Gets the value of the relatedPlannedTransportIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedPlannedTransportIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedPlannedTransportIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompositIdentifierPlannedType }
     * 
     * 
     */
    public List<CompositIdentifierPlannedType> getRelatedPlannedTransportIdentifiers() {
        if (relatedPlannedTransportIdentifiers == null) {
            relatedPlannedTransportIdentifiers = new ArrayList<CompositIdentifierPlannedType>();
        }
        return this.relatedPlannedTransportIdentifiers;
    }

}
