//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Location"/>
 *         &lt;element name="DetailedDescriptionOfLocation" type="{http://taf-jsg.info/schemes}FreeText" minOccurs="0"/>
 *         &lt;element name="Interruption">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}InterruptionReason" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}InterruptionDateTime"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}InterruptionDescription" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}InternalReferenceIdentifier" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="InterruptionDuration" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EarliestEndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="LatestEndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Remarks" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "location",
    "detailedDescriptionOfLocation",
    "interruption",
    "interruptionDuration",
    "remarks"
})
@XmlRootElement(name = "InterruptionPoint")
public class InterruptionPoint {

    @XmlElement(name = "Location", required = true)
    protected LocationIdent location;
    @XmlElement(name = "DetailedDescriptionOfLocation")
    protected String detailedDescriptionOfLocation;
    @XmlElement(name = "Interruption", required = true)
    protected InterruptionPoint.Interruption interruption;
    @XmlElement(name = "InterruptionDuration")
    protected InterruptionPoint.InterruptionDuration interruptionDuration;
    @XmlElement(name = "Remarks")
    protected List<String> remarks;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setLocation(LocationIdent value) {
        this.location = value;
    }

    /**
     * Gets the value of the detailedDescriptionOfLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetailedDescriptionOfLocation() {
        return detailedDescriptionOfLocation;
    }

    /**
     * Sets the value of the detailedDescriptionOfLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetailedDescriptionOfLocation(String value) {
        this.detailedDescriptionOfLocation = value;
    }

    /**
     * Gets the value of the interruption property.
     * 
     * @return
     *     possible object is
     *     {@link InterruptionPoint.Interruption }
     *     
     */
    public InterruptionPoint.Interruption getInterruption() {
        return interruption;
    }

    /**
     * Sets the value of the interruption property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterruptionPoint.Interruption }
     *     
     */
    public void setInterruption(InterruptionPoint.Interruption value) {
        this.interruption = value;
    }

    /**
     * Gets the value of the interruptionDuration property.
     * 
     * @return
     *     possible object is
     *     {@link InterruptionPoint.InterruptionDuration }
     *     
     */
    public InterruptionPoint.InterruptionDuration getInterruptionDuration() {
        return interruptionDuration;
    }

    /**
     * Sets the value of the interruptionDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterruptionPoint.InterruptionDuration }
     *     
     */
    public void setInterruptionDuration(InterruptionPoint.InterruptionDuration value) {
        this.interruptionDuration = value;
    }

    /**
     * To provide any additional information to the RU
     * 							or next IM (e.g. contact person, next steps, etc)
     * 						Gets the value of the remarks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remarks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemarks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRemarks() {
        if (remarks == null) {
            remarks = new ArrayList<String>();
        }
        return this.remarks;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://taf-jsg.info/schemes}InterruptionReason" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}InterruptionDateTime"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}InterruptionDescription" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}InternalReferenceIdentifier" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "interruptionReason",
        "interruptionDateTime",
        "interruptionDescription",
        "internalReferenceIdentifier"
    })
    public static class Interruption {

        @XmlElement(name = "InterruptionReason")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String interruptionReason;
        @XmlElement(name = "InterruptionDateTime", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar interruptionDateTime;
        @XmlElement(name = "InterruptionDescription")
        protected List<String> interruptionDescription;
        @XmlElement(name = "InternalReferenceIdentifier")
        protected String internalReferenceIdentifier;

        /**
         * Gets the value of the interruptionReason property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterruptionReason() {
            return interruptionReason;
        }

        /**
         * Sets the value of the interruptionReason property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterruptionReason(String value) {
            this.interruptionReason = value;
        }

        /**
         * Gets the value of the interruptionDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getInterruptionDateTime() {
            return interruptionDateTime;
        }

        /**
         * Sets the value of the interruptionDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setInterruptionDateTime(XMLGregorianCalendar value) {
            this.interruptionDateTime = value;
        }

        /**
         * Gets the value of the interruptionDescription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the interruptionDescription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInterruptionDescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getInterruptionDescription() {
            if (interruptionDescription == null) {
                interruptionDescription = new ArrayList<String>();
            }
            return this.interruptionDescription;
        }

        /**
         * Gets the value of the internalReferenceIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInternalReferenceIdentifier() {
            return internalReferenceIdentifier;
        }

        /**
         * Sets the value of the internalReferenceIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInternalReferenceIdentifier(String value) {
            this.internalReferenceIdentifier = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EarliestEndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="LatestEndDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "earliestEndDateTime",
        "latestEndDateTime"
    })
    public static class InterruptionDuration {

        @XmlElement(name = "EarliestEndDateTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar earliestEndDateTime;
        @XmlElement(name = "LatestEndDateTime")
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar latestEndDateTime;

        /**
         * Gets the value of the earliestEndDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getEarliestEndDateTime() {
            return earliestEndDateTime;
        }

        /**
         * Sets the value of the earliestEndDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setEarliestEndDateTime(XMLGregorianCalendar value) {
            this.earliestEndDateTime = value;
        }

        /**
         * Gets the value of the latestEndDateTime property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLatestEndDateTime() {
            return latestEndDateTime;
        }

        /**
         * Sets the value of the latestEndDateTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLatestEndDateTime(XMLGregorianCalendar value) {
            this.latestEndDateTime = value;
        }

    }

}
