//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ITU_Type"/>
 *         &lt;element name="Number">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://taf-jsg.info/schemes}EquipmentNumberType">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LoadingStatus"/>
 *         &lt;element name="ITU_TypeDetail">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *               &lt;enumeration value="BX"/>
 *               &lt;enumeration value="BK"/>
 *               &lt;enumeration value="FL"/>
 *               &lt;enumeration value="HT"/>
 *               &lt;enumeration value="HC"/>
 *               &lt;enumeration value="IN"/>
 *               &lt;enumeration value="OT"/>
 *               &lt;enumeration value="HH"/>
 *               &lt;enumeration value="PW"/>
 *               &lt;enumeration value="OS"/>
 *               &lt;enumeration value="RF"/>
 *               &lt;enumeration value="SD"/>
 *               &lt;enumeration value="SL"/>
 *               &lt;enumeration value="VE"/>
 *               &lt;enumeration value="TC"/>
 *               &lt;enumeration value="RH"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Prefix" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Checkdigit" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Dimensions"/>
 *         &lt;element name="TareWeight" type="{http://taf-jsg.info/schemes}WeightValueKilo"/>
 *         &lt;element name="SwapBodyCodification" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="3"/>
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Forwarding" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="80"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Ship" minOccurs="0"/>
 *         &lt;element name="TurnInNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}DeliveryReference" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}OriginCountry" minOccurs="0"/>
 *         &lt;element name="DepartureCountry" type="{http://taf-jsg.info/schemes}CountryIdentISO" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}UltimateDestinationCountry" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Seals" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ReferenceNumbers" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ituType",
    "number",
    "loadingStatus",
    "ituTypeDetail",
    "prefix",
    "checkdigit",
    "dimensions",
    "tareWeight",
    "swapBodyCodification",
    "forwarding",
    "ship",
    "turnInNumber",
    "deliveryReference",
    "originCountry",
    "departureCountry",
    "ultimateDestinationCountry",
    "seals",
    "referenceNumbers"
})
@XmlRootElement(name = "ITU_Details")
public class ITUDetails {

    @XmlElement(name = "ITU_Type", required = true)
    protected EquipmentTypeType ituType;
    @XmlElement(name = "Number", required = true)
    protected String number;
    @XmlElement(name = "LoadingStatus", required = true)
    protected BigInteger loadingStatus;
    @XmlElement(name = "ITU_TypeDetail", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String ituTypeDetail;
    @XmlElement(name = "Prefix")
    protected String prefix;
    @XmlElement(name = "Checkdigit")
    protected Integer checkdigit;
    @XmlElement(name = "Dimensions", required = true)
    protected Dimensions dimensions;
    @XmlElement(name = "TareWeight")
    protected int tareWeight;
    @XmlElement(name = "SwapBodyCodification")
    protected String swapBodyCodification;
    @XmlElement(name = "Forwarding")
    protected String forwarding;
    @XmlElement(name = "Ship")
    protected Ship ship;
    @XmlElement(name = "TurnInNumber")
    protected String turnInNumber;
    @XmlElement(name = "DeliveryReference")
    protected String deliveryReference;
    @XmlElement(name = "OriginCountry")
    protected String originCountry;
    @XmlElement(name = "DepartureCountry")
    protected String departureCountry;
    @XmlElement(name = "UltimateDestinationCountry")
    protected String ultimateDestinationCountry;
    @XmlElement(name = "Seals")
    protected Seals seals;
    @XmlElement(name = "ReferenceNumbers")
    protected ReferenceNumbers referenceNumbers;

    /**
     * Type of Intermodal Transport Unit. Further
     * 							information is given for each enumeration element.
     * 						
     * 
     * @return
     *     possible object is
     *     {@link EquipmentTypeType }
     *     
     */
    public EquipmentTypeType getITUType() {
        return ituType;
    }

    /**
     * Sets the value of the ituType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EquipmentTypeType }
     *     
     */
    public void setITUType(EquipmentTypeType value) {
        this.ituType = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the loadingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLoadingStatus() {
        return loadingStatus;
    }

    /**
     * Sets the value of the loadingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLoadingStatus(BigInteger value) {
        this.loadingStatus = value;
    }

    /**
     * Gets the value of the ituTypeDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITUTypeDetail() {
        return ituTypeDetail;
    }

    /**
     * Sets the value of the ituTypeDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITUTypeDetail(String value) {
        this.ituTypeDetail = value;
    }

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefix(String value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the checkdigit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCheckdigit() {
        return checkdigit;
    }

    /**
     * Sets the value of the checkdigit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCheckdigit(Integer value) {
        this.checkdigit = value;
    }

    /**
     * Gets the value of the dimensions property.
     * 
     * @return
     *     possible object is
     *     {@link Dimensions }
     *     
     */
    public Dimensions getDimensions() {
        return dimensions;
    }

    /**
     * Sets the value of the dimensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dimensions }
     *     
     */
    public void setDimensions(Dimensions value) {
        this.dimensions = value;
    }

    /**
     * Gets the value of the tareWeight property.
     * 
     */
    public int getTareWeight() {
        return tareWeight;
    }

    /**
     * Sets the value of the tareWeight property.
     * 
     */
    public void setTareWeight(int value) {
        this.tareWeight = value;
    }

    /**
     * Gets the value of the swapBodyCodification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwapBodyCodification() {
        return swapBodyCodification;
    }

    /**
     * Sets the value of the swapBodyCodification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwapBodyCodification(String value) {
        this.swapBodyCodification = value;
    }

    /**
     * Gets the value of the forwarding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForwarding() {
        return forwarding;
    }

    /**
     * Sets the value of the forwarding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForwarding(String value) {
        this.forwarding = value;
    }

    /**
     * Gets the value of the ship property.
     * 
     * @return
     *     possible object is
     *     {@link Ship }
     *     
     */
    public Ship getShip() {
        return ship;
    }

    /**
     * Sets the value of the ship property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ship }
     *     
     */
    public void setShip(Ship value) {
        this.ship = value;
    }

    /**
     * Gets the value of the turnInNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTurnInNumber() {
        return turnInNumber;
    }

    /**
     * Sets the value of the turnInNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTurnInNumber(String value) {
        this.turnInNumber = value;
    }

    /**
     * Gets the value of the deliveryReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryReference() {
        return deliveryReference;
    }

    /**
     * Sets the value of the deliveryReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryReference(String value) {
        this.deliveryReference = value;
    }

    /**
     * Gets the value of the originCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginCountry() {
        return originCountry;
    }

    /**
     * Sets the value of the originCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginCountry(String value) {
        this.originCountry = value;
    }

    /**
     * Gets the value of the departureCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartureCountry() {
        return departureCountry;
    }

    /**
     * Sets the value of the departureCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartureCountry(String value) {
        this.departureCountry = value;
    }

    /**
     * Gets the value of the ultimateDestinationCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUltimateDestinationCountry() {
        return ultimateDestinationCountry;
    }

    /**
     * Sets the value of the ultimateDestinationCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUltimateDestinationCountry(String value) {
        this.ultimateDestinationCountry = value;
    }

    /**
     * Gets the value of the seals property.
     * 
     * @return
     *     possible object is
     *     {@link Seals }
     *     
     */
    public Seals getSeals() {
        return seals;
    }

    /**
     * Sets the value of the seals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Seals }
     *     
     */
    public void setSeals(Seals value) {
        this.seals = value;
    }

    /**
     * Gets the value of the referenceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceNumbers }
     *     
     */
    public ReferenceNumbers getReferenceNumbers() {
        return referenceNumbers;
    }

    /**
     * Sets the value of the referenceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceNumbers }
     *     
     */
    public void setReferenceNumbers(ReferenceNumbers value) {
        this.referenceNumbers = value;
    }

}
