//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Location"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ModificationStatusIndicator"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainLocationStatus" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}BookedLocationDateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "location",
    "modificationStatusIndicator",
    "trainLocationStatus",
    "bookedLocationDateTime"
})
@XmlRootElement(name = "LocationModified")
public class LocationModified {

    @XmlElement(name = "Location", required = true)
    protected LocationIdent location;
    @XmlElement(name = "ModificationStatusIndicator")
    protected int modificationStatusIndicator;
    @XmlElement(name = "TrainLocationStatus")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String trainLocationStatus;
    @XmlElement(name = "BookedLocationDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar bookedLocationDateTime;

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setLocation(LocationIdent value) {
        this.location = value;
    }

    /**
     * Gets the value of the modificationStatusIndicator property.
     * 
     */
    public int getModificationStatusIndicator() {
        return modificationStatusIndicator;
    }

    /**
     * Sets the value of the modificationStatusIndicator property.
     * 
     */
    public void setModificationStatusIndicator(int value) {
        this.modificationStatusIndicator = value;
    }

    /**
     * Gets the value of the trainLocationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainLocationStatus() {
        return trainLocationStatus;
    }

    /**
     * Sets the value of the trainLocationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainLocationStatus(String value) {
        this.trainLocationStatus = value;
    }

    /**
     * Gets the value of the bookedLocationDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBookedLocationDateTime() {
        return bookedLocationDateTime;
    }

    /**
     * Sets the value of the bookedLocationDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBookedLocationDateTime(XMLGregorianCalendar value) {
        this.bookedLocationDateTime = value;
    }

}
