//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LocationPrimaryName"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ResponsibleIM"/>
 *         &lt;element name="PrimaryLocationNameASCII">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="255"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LocationValidityPeriod"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ContainerHandlingFlag" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}HandoverPointFlag" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://taf-jsg.info/schemes}FreightFlag"/>
 *           &lt;element name="FreightValidityPeriod" type="{http://taf-jsg.info/schemes}ValidityPeriod1" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://taf-jsg.info/schemes}PassengerFlag"/>
 *           &lt;element name="PassengerValidityPeriod" type="{http://taf-jsg.info/schemes}ValidityPeriod1" minOccurs="0"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}GeographicCoordinates" minOccurs="0"/>
 *         &lt;element name="NUTS_Code" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Comments" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locationPrimaryName",
    "responsibleIM",
    "primaryLocationNameASCII",
    "locationValidityPeriod",
    "containerHandlingFlag",
    "handoverPointFlag",
    "freightFlag",
    "freightValidityPeriod",
    "passengerFlag",
    "passengerValidityPeriod",
    "geographicCoordinates",
    "nutsCode",
    "comments"
})
@XmlRootElement(name = "LocationPrimaryInformation")
public class LocationPrimaryInformation {

    @XmlElement(name = "LocationPrimaryName", required = true)
    protected Object locationPrimaryName;
    @XmlElement(name = "ResponsibleIM")
    protected int responsibleIM;
    @XmlElement(name = "PrimaryLocationNameASCII", required = true)
    protected String primaryLocationNameASCII;
    @XmlElement(name = "LocationValidityPeriod", required = true)
    protected ValidityPeriod1 locationValidityPeriod;
    @XmlElement(name = "ContainerHandlingFlag")
    protected Boolean containerHandlingFlag;
    @XmlElement(name = "HandoverPointFlag")
    protected Object handoverPointFlag;
    @XmlElement(name = "FreightFlag")
    protected Boolean freightFlag;
    @XmlElement(name = "FreightValidityPeriod")
    protected ValidityPeriod1 freightValidityPeriod;
    @XmlElement(name = "PassengerFlag")
    protected Boolean passengerFlag;
    @XmlElement(name = "PassengerValidityPeriod")
    protected ValidityPeriod1 passengerValidityPeriod;
    @XmlElement(name = "GeographicCoordinates")
    protected GeographicCoordinates geographicCoordinates;
    @XmlElement(name = "NUTS_Code")
    protected String nutsCode;
    @XmlElement(name = "Comments")
    protected String comments;

    /**
     * Gets the value of the locationPrimaryName property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLocationPrimaryName() {
        return locationPrimaryName;
    }

    /**
     * Sets the value of the locationPrimaryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLocationPrimaryName(Object value) {
        this.locationPrimaryName = value;
    }

    /**
     * Gets the value of the responsibleIM property.
     * 
     */
    public int getResponsibleIM() {
        return responsibleIM;
    }

    /**
     * Sets the value of the responsibleIM property.
     * 
     */
    public void setResponsibleIM(int value) {
        this.responsibleIM = value;
    }

    /**
     * Gets the value of the primaryLocationNameASCII property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryLocationNameASCII() {
        return primaryLocationNameASCII;
    }

    /**
     * Sets the value of the primaryLocationNameASCII property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryLocationNameASCII(String value) {
        this.primaryLocationNameASCII = value;
    }

    /**
     * Gets the value of the locationValidityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ValidityPeriod1 }
     *     
     */
    public ValidityPeriod1 getLocationValidityPeriod() {
        return locationValidityPeriod;
    }

    /**
     * Sets the value of the locationValidityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidityPeriod1 }
     *     
     */
    public void setLocationValidityPeriod(ValidityPeriod1 value) {
        this.locationValidityPeriod = value;
    }

    /**
     * Gets the value of the containerHandlingFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isContainerHandlingFlag() {
        return containerHandlingFlag;
    }

    /**
     * Sets the value of the containerHandlingFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setContainerHandlingFlag(Boolean value) {
        this.containerHandlingFlag = value;
    }

    /**
     * Gets the value of the handoverPointFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getHandoverPointFlag() {
        return handoverPointFlag;
    }

    /**
     * Sets the value of the handoverPointFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setHandoverPointFlag(Object value) {
        this.handoverPointFlag = value;
    }

    /**
     * Gets the value of the freightFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isFreightFlag() {
        return freightFlag;
    }

    /**
     * Sets the value of the freightFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setFreightFlag(Boolean value) {
        this.freightFlag = value;
    }

    /**
     * Gets the value of the freightValidityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ValidityPeriod1 }
     *     
     */
    public ValidityPeriod1 getFreightValidityPeriod() {
        return freightValidityPeriod;
    }

    /**
     * Sets the value of the freightValidityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidityPeriod1 }
     *     
     */
    public void setFreightValidityPeriod(ValidityPeriod1 value) {
        this.freightValidityPeriod = value;
    }

    /**
     * Gets the value of the passengerFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPassengerFlag() {
        return passengerFlag;
    }

    /**
     * Sets the value of the passengerFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPassengerFlag(Boolean value) {
        this.passengerFlag = value;
    }

    /**
     * Gets the value of the passengerValidityPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link ValidityPeriod1 }
     *     
     */
    public ValidityPeriod1 getPassengerValidityPeriod() {
        return passengerValidityPeriod;
    }

    /**
     * Sets the value of the passengerValidityPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidityPeriod1 }
     *     
     */
    public void setPassengerValidityPeriod(ValidityPeriod1 value) {
        this.passengerValidityPeriod = value;
    }

    /**
     * Gets the value of the geographicCoordinates property.
     * 
     * @return
     *     possible object is
     *     {@link GeographicCoordinates }
     *     
     */
    public GeographicCoordinates getGeographicCoordinates() {
        return geographicCoordinates;
    }

    /**
     * Sets the value of the geographicCoordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeographicCoordinates }
     *     
     */
    public void setGeographicCoordinates(GeographicCoordinates value) {
        this.geographicCoordinates = value;
    }

    /**
     * Gets the value of the nutsCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUTSCode() {
        return nutsCode;
    }

    /**
     * Sets the value of the nutsCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUTSCode(String value) {
        this.nutsCode = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComments() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComments(String value) {
        this.comments = value;
    }

}
