//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}OperationalTrainNumber"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ScheduledTimeAtHandover" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ScheduledDateTimeAtTransfer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "operationalTrainNumber",
    "scheduledTimeAtHandover",
    "scheduledDateTimeAtTransfer"
})
@XmlRootElement(name = "OperationalTrainNumberIdentifier")
public class OperationalTrainNumberIdentifier {

    @XmlElement(name = "OperationalTrainNumber", required = true)
    protected String operationalTrainNumber;
    @XmlElement(name = "ScheduledTimeAtHandover")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduledTimeAtHandover;
    @XmlElement(name = "ScheduledDateTimeAtTransfer")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar scheduledDateTimeAtTransfer;

    /**
     * Gets the value of the operationalTrainNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalTrainNumber() {
        return operationalTrainNumber;
    }

    /**
     * Sets the value of the operationalTrainNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalTrainNumber(String value) {
        this.operationalTrainNumber = value;
    }

    /**
     * Gets the value of the scheduledTimeAtHandover property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduledTimeAtHandover() {
        return scheduledTimeAtHandover;
    }

    /**
     * Sets the value of the scheduledTimeAtHandover property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduledTimeAtHandover(XMLGregorianCalendar value) {
        this.scheduledTimeAtHandover = value;
    }

    /**
     * Gets the value of the scheduledDateTimeAtTransfer property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getScheduledDateTimeAtTransfer() {
        return scheduledDateTimeAtTransfer;
    }

    /**
     * Sets the value of the scheduledDateTimeAtTransfer property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setScheduledDateTimeAtTransfer(XMLGregorianCalendar value) {
        this.scheduledDateTimeAtTransfer = value;
    }

}
