//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageHeader"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageStatus"/>
 *         &lt;choice>
 *           &lt;element ref="{http://taf-jsg.info/schemes}PlannedTransportIdentifiers" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://taf-jsg.info/schemes}TransportOperationalIdentifiers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://taf-jsg.info/schemes}OperationalTrainNumberIdentifier" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ReferenceOTN" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TransfereeIM" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TransferPoint" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainDepartureStation" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainDestinationStation" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainCompositionJourneySectionPassenger" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Parameters" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Remarks" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeader",
    "messageStatus",
    "plannedTransportIdentifiers",
    "transportOperationalIdentifiers",
    "operationalTrainNumberIdentifier",
    "referenceOTN",
    "transfereeIM",
    "transferPoint",
    "trainDepartureStation",
    "trainDestinationStation",
    "trainCompositionJourneySectionPassenger",
    "parameters",
    "remarks"
})
@XmlRootElement(name = "PassengerTrainCompositionProcessMessage")
public class PassengerTrainCompositionProcessMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeader messageHeader;
    @XmlElement(name = "MessageStatus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String messageStatus;
    @XmlElement(name = "PlannedTransportIdentifiers")
    protected List<CompositIdentifierPlannedType> plannedTransportIdentifiers;
    @XmlElement(name = "TransportOperationalIdentifiers")
    protected List<TransportOperationalIdentifiers> transportOperationalIdentifiers;
    @XmlElement(name = "OperationalTrainNumberIdentifier")
    protected OperationalTrainNumberIdentifier operationalTrainNumberIdentifier;
    @XmlElement(name = "ReferenceOTN")
    protected ReferenceOTN referenceOTN;
    @XmlElement(name = "TransfereeIM")
    protected Integer transfereeIM;
    @XmlElement(name = "TransferPoint")
    protected LocationIdent transferPoint;
    @XmlElement(name = "TrainDepartureStation")
    protected LocationIdent trainDepartureStation;
    @XmlElement(name = "TrainDestinationStation")
    protected LocationIdent trainDestinationStation;
    @XmlElement(name = "TrainCompositionJourneySectionPassenger", required = true)
    protected List<TrainCompositionJourneySectionPassenger> trainCompositionJourneySectionPassenger;
    @XmlElement(name = "Parameters")
    protected List<Parameters> parameters;
    @XmlElement(name = "Remarks")
    protected String remarks;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the messageStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageStatus() {
        return messageStatus;
    }

    /**
     * Sets the value of the messageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageStatus(String value) {
        this.messageStatus = value;
    }

    /**
     * Gets the value of the plannedTransportIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedTransportIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedTransportIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompositIdentifierPlannedType }
     * 
     * 
     */
    public List<CompositIdentifierPlannedType> getPlannedTransportIdentifiers() {
        if (plannedTransportIdentifiers == null) {
            plannedTransportIdentifiers = new ArrayList<CompositIdentifierPlannedType>();
        }
        return this.plannedTransportIdentifiers;
    }

    /**
     * Gets the value of the transportOperationalIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportOperationalIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportOperationalIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportOperationalIdentifiers }
     * 
     * 
     */
    public List<TransportOperationalIdentifiers> getTransportOperationalIdentifiers() {
        if (transportOperationalIdentifiers == null) {
            transportOperationalIdentifiers = new ArrayList<TransportOperationalIdentifiers>();
        }
        return this.transportOperationalIdentifiers;
    }

    /**
     * Gets the value of the operationalTrainNumberIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalTrainNumberIdentifier }
     *     
     */
    public OperationalTrainNumberIdentifier getOperationalTrainNumberIdentifier() {
        return operationalTrainNumberIdentifier;
    }

    /**
     * Sets the value of the operationalTrainNumberIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalTrainNumberIdentifier }
     *     
     */
    public void setOperationalTrainNumberIdentifier(OperationalTrainNumberIdentifier value) {
        this.operationalTrainNumberIdentifier = value;
    }

    /**
     * Gets the value of the referenceOTN property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceOTN }
     *     
     */
    public ReferenceOTN getReferenceOTN() {
        return referenceOTN;
    }

    /**
     * Sets the value of the referenceOTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceOTN }
     *     
     */
    public void setReferenceOTN(ReferenceOTN value) {
        this.referenceOTN = value;
    }

    /**
     * Gets the value of the transfereeIM property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransfereeIM() {
        return transfereeIM;
    }

    /**
     * Sets the value of the transfereeIM property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransfereeIM(Integer value) {
        this.transfereeIM = value;
    }

    /**
     * Gets the value of the transferPoint property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getTransferPoint() {
        return transferPoint;
    }

    /**
     * Sets the value of the transferPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setTransferPoint(LocationIdent value) {
        this.transferPoint = value;
    }

    /**
     * Gets the value of the trainDepartureStation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getTrainDepartureStation() {
        return trainDepartureStation;
    }

    /**
     * Sets the value of the trainDepartureStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setTrainDepartureStation(LocationIdent value) {
        this.trainDepartureStation = value;
    }

    /**
     * Gets the value of the trainDestinationStation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getTrainDestinationStation() {
        return trainDestinationStation;
    }

    /**
     * Sets the value of the trainDestinationStation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setTrainDestinationStation(LocationIdent value) {
        this.trainDestinationStation = value;
    }

    /**
     * Gets the value of the trainCompositionJourneySectionPassenger property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainCompositionJourneySectionPassenger property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainCompositionJourneySectionPassenger().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrainCompositionJourneySectionPassenger }
     * 
     * 
     */
    public List<TrainCompositionJourneySectionPassenger> getTrainCompositionJourneySectionPassenger() {
        if (trainCompositionJourneySectionPassenger == null) {
            trainCompositionJourneySectionPassenger = new ArrayList<TrainCompositionJourneySectionPassenger>();
        }
        return this.trainCompositionJourneySectionPassenger;
    }

    /**
     * Gets the value of the parameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Parameters }
     * 
     * 
     */
    public List<Parameters> getParameters() {
        if (parameters == null) {
            parameters = new ArrayList<Parameters>();
        }
        return this.parameters;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

}
