//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainType" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrafficType" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TypeofService" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}CommercialTrafficType" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}PlannedTrainTechnicalData"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ExceptionalGaugingIdent" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}DangerousGoodsIndication" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}CombinedTrafficLoadProfile" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trainType",
    "trafficType",
    "typeofService",
    "commercialTrafficType",
    "plannedTrainTechnicalData",
    "exceptionalGaugingIdent",
    "dangerousGoodsIndication",
    "combinedTrafficLoadProfile"
})
@XmlRootElement(name = "PlannedTrainData")
public class PlannedTrainData {

    @XmlElement(name = "TrainType")
    protected BigInteger trainType;
    @XmlElement(name = "TrafficType")
    protected String trafficType;
    @XmlElement(name = "TypeofService")
    protected TypeofService typeofService;
    @XmlElement(name = "CommercialTrafficType")
    protected BigInteger commercialTrafficType;
    @XmlElement(name = "PlannedTrainTechnicalData", required = true)
    protected PlannedTrainTechnicalData plannedTrainTechnicalData;
    @XmlElement(name = "ExceptionalGaugingIdent")
    protected List<ExceptionalGaugingIdent> exceptionalGaugingIdent;
    @XmlElement(name = "DangerousGoodsIndication")
    protected List<DanGoodsType> dangerousGoodsIndication;
    @XmlElement(name = "CombinedTrafficLoadProfile")
    protected CombinedTrafficLoadProfile combinedTrafficLoadProfile;

    /**
     * Gets the value of the trainType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrainType() {
        return trainType;
    }

    /**
     * Sets the value of the trainType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrainType(BigInteger value) {
        this.trainType = value;
    }

    /**
     * Gets the value of the trafficType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrafficType() {
        return trafficType;
    }

    /**
     * Sets the value of the trafficType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrafficType(String value) {
        this.trafficType = value;
    }

    /**
     * Gets the value of the typeofService property.
     * 
     * @return
     *     possible object is
     *     {@link TypeofService }
     *     
     */
    public TypeofService getTypeofService() {
        return typeofService;
    }

    /**
     * Sets the value of the typeofService property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeofService }
     *     
     */
    public void setTypeofService(TypeofService value) {
        this.typeofService = value;
    }

    /**
     * Gets the value of the commercialTrafficType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCommercialTrafficType() {
        return commercialTrafficType;
    }

    /**
     * Sets the value of the commercialTrafficType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCommercialTrafficType(BigInteger value) {
        this.commercialTrafficType = value;
    }

    /**
     * Gets the value of the plannedTrainTechnicalData property.
     * 
     * @return
     *     possible object is
     *     {@link PlannedTrainTechnicalData }
     *     
     */
    public PlannedTrainTechnicalData getPlannedTrainTechnicalData() {
        return plannedTrainTechnicalData;
    }

    /**
     * Sets the value of the plannedTrainTechnicalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlannedTrainTechnicalData }
     *     
     */
    public void setPlannedTrainTechnicalData(PlannedTrainTechnicalData value) {
        this.plannedTrainTechnicalData = value;
    }

    /**
     * Gets the value of the exceptionalGaugingIdent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exceptionalGaugingIdent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExceptionalGaugingIdent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExceptionalGaugingIdent }
     * 
     * 
     */
    public List<ExceptionalGaugingIdent> getExceptionalGaugingIdent() {
        if (exceptionalGaugingIdent == null) {
            exceptionalGaugingIdent = new ArrayList<ExceptionalGaugingIdent>();
        }
        return this.exceptionalGaugingIdent;
    }

    /**
     * Gets the value of the dangerousGoodsIndication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dangerousGoodsIndication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDangerousGoodsIndication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DanGoodsType }
     * 
     * 
     */
    public List<DanGoodsType> getDangerousGoodsIndication() {
        if (dangerousGoodsIndication == null) {
            dangerousGoodsIndication = new ArrayList<DanGoodsType>();
        }
        return this.dangerousGoodsIndication;
    }

    /**
     * Gets the value of the combinedTrafficLoadProfile property.
     * 
     * @return
     *     possible object is
     *     {@link CombinedTrafficLoadProfile }
     *     
     */
    public CombinedTrafficLoadProfile getCombinedTrafficLoadProfile() {
        return combinedTrafficLoadProfile;
    }

    /**
     * Sets the value of the combinedTrafficLoadProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link CombinedTrafficLoadProfile }
     *     
     */
    public void setCombinedTrafficLoadProfile(CombinedTrafficLoadProfile value) {
        this.combinedTrafficLoadProfile = value;
    }

}
