//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="99">
 *         &lt;element name="MovementReferenceNumber" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}MRN_Type"/>
 *                   &lt;element name="MRN_Number">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="21"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ARC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="21"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "movementReferenceNumberAndARC"
})
@XmlRootElement(name = "ReferenceNumbers")
public class ReferenceNumbers {

    @XmlElements({
        @XmlElement(name = "MovementReferenceNumber", type = ReferenceNumbers.MovementReferenceNumber.class),
        @XmlElement(name = "ARC", type = String.class)
    })
    protected List<Object> movementReferenceNumberAndARC;

    /**
     * Gets the value of the movementReferenceNumberAndARC property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the movementReferenceNumberAndARC property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMovementReferenceNumberAndARC().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceNumbers.MovementReferenceNumber }
     * {@link String }
     * 
     * 
     */
    public List<Object> getMovementReferenceNumberAndARC() {
        if (movementReferenceNumberAndARC == null) {
            movementReferenceNumberAndARC = new ArrayList<Object>();
        }
        return this.movementReferenceNumberAndARC;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://taf-jsg.info/schemes}MRN_Type"/>
     *         &lt;element name="MRN_Number">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="21"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mrnType",
        "mrnNumber"
    })
    public static class MovementReferenceNumber {

        @XmlElement(name = "MRN_Type", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String mrnType;
        @XmlElement(name = "MRN_Number", required = true)
        protected String mrnNumber;

        /**
         * Gets the value of the mrnType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMRNType() {
            return mrnType;
        }

        /**
         * Sets the value of the mrnType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMRNType(String value) {
            this.mrnType = value;
        }

        /**
         * Gets the value of the mrnNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMRNNumber() {
            return mrnNumber;
        }

        /**
         * Sets the value of the mrnNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMRNNumber(String value) {
            this.mrnNumber = value;
        }

    }

}
