//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Law">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;enumeration value="2013"/>
 *               &lt;enumeration value="2015"/>
 *               &lt;enumeration value="2017"/>
 *               &lt;enumeration value="2019"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}DangerousGoodsIndication"/>
 *         &lt;element name="TechnicalDescription" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="350"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ProperShippingName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="350"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SpecialProvisionsRID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="350"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AdditionalProvisionsRID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="350"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ActionRequiredFromCarrier" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="350"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WeightNettoExplosiveMass" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;minInclusive value="0"/>
 *               &lt;fractionDigits value="1"/>
 *               &lt;totalDigits value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ClassificationCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EmptyPackingCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="01"/>
 *               &lt;enumeration value="02"/>
 *               &lt;enumeration value="03"/>
 *               &lt;enumeration value="04"/>
 *               &lt;enumeration value="05"/>
 *               &lt;enumeration value="06"/>
 *               &lt;enumeration value="07"/>
 *               &lt;enumeration value="08"/>
 *               &lt;enumeration value="09"/>
 *               &lt;enumeration value="10"/>
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="13"/>
 *               &lt;enumeration value="14"/>
 *               &lt;enumeration value="15"/>
 *               &lt;enumeration value="16"/>
 *               &lt;enumeration value="17"/>
 *               &lt;enumeration value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "law",
    "dangerousGoodsIndication",
    "technicalDescription",
    "properShippingName",
    "specialProvisionsRID",
    "additionalProvisionsRID",
    "actionRequiredFromCarrier",
    "weightNettoExplosiveMass",
    "classificationCode",
    "emptyPackingCode"
})
@XmlRootElement(name = "RID")
public class RID {

    @XmlElement(name = "Law")
    protected int law;
    @XmlElement(name = "DangerousGoodsIndication", required = true)
    protected DanGoodsType dangerousGoodsIndication;
    @XmlElement(name = "TechnicalDescription")
    protected String technicalDescription;
    @XmlElement(name = "ProperShippingName")
    protected String properShippingName;
    @XmlElement(name = "SpecialProvisionsRID")
    protected String specialProvisionsRID;
    @XmlElement(name = "AdditionalProvisionsRID")
    protected String additionalProvisionsRID;
    @XmlElement(name = "ActionRequiredFromCarrier")
    protected String actionRequiredFromCarrier;
    @XmlElement(name = "WeightNettoExplosiveMass")
    protected BigDecimal weightNettoExplosiveMass;
    @XmlElement(name = "ClassificationCode")
    protected String classificationCode;
    @XmlElement(name = "EmptyPackingCode")
    protected String emptyPackingCode;

    /**
     * Gets the value of the law property.
     * 
     */
    public int getLaw() {
        return law;
    }

    /**
     * Sets the value of the law property.
     * 
     */
    public void setLaw(int value) {
        this.law = value;
    }

    /**
     * Gets the value of the dangerousGoodsIndication property.
     * 
     * @return
     *     possible object is
     *     {@link DanGoodsType }
     *     
     */
    public DanGoodsType getDangerousGoodsIndication() {
        return dangerousGoodsIndication;
    }

    /**
     * Sets the value of the dangerousGoodsIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link DanGoodsType }
     *     
     */
    public void setDangerousGoodsIndication(DanGoodsType value) {
        this.dangerousGoodsIndication = value;
    }

    /**
     * Gets the value of the technicalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnicalDescription() {
        return technicalDescription;
    }

    /**
     * Sets the value of the technicalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnicalDescription(String value) {
        this.technicalDescription = value;
    }

    /**
     * Gets the value of the properShippingName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProperShippingName() {
        return properShippingName;
    }

    /**
     * Sets the value of the properShippingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProperShippingName(String value) {
        this.properShippingName = value;
    }

    /**
     * Gets the value of the specialProvisionsRID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialProvisionsRID() {
        return specialProvisionsRID;
    }

    /**
     * Sets the value of the specialProvisionsRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialProvisionsRID(String value) {
        this.specialProvisionsRID = value;
    }

    /**
     * Gets the value of the additionalProvisionsRID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdditionalProvisionsRID() {
        return additionalProvisionsRID;
    }

    /**
     * Sets the value of the additionalProvisionsRID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdditionalProvisionsRID(String value) {
        this.additionalProvisionsRID = value;
    }

    /**
     * Gets the value of the actionRequiredFromCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionRequiredFromCarrier() {
        return actionRequiredFromCarrier;
    }

    /**
     * Sets the value of the actionRequiredFromCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionRequiredFromCarrier(String value) {
        this.actionRequiredFromCarrier = value;
    }

    /**
     * Gets the value of the weightNettoExplosiveMass property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeightNettoExplosiveMass() {
        return weightNettoExplosiveMass;
    }

    /**
     * Sets the value of the weightNettoExplosiveMass property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeightNettoExplosiveMass(BigDecimal value) {
        this.weightNettoExplosiveMass = value;
    }

    /**
     * Gets the value of the classificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationCode() {
        return classificationCode;
    }

    /**
     * Sets the value of the classificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationCode(String value) {
        this.classificationCode = value;
    }

    /**
     * Gets the value of the emptyPackingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmptyPackingCode() {
        return emptyPackingCode;
    }

    /**
     * Sets the value of the emptyPackingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmptyPackingCode(String value) {
        this.emptyPackingCode = value;
    }

}
