//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}NumberOfAxles" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonMaxSpeed" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LengthOverBuffers" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonWeightEmpty" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TotalLoadWeight" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LoadingGauge" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ExceptionalGaugingProfile" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ExceptionalGaugingIdent" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TypeOfHeating" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}HandBrake" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}AirBrake" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}AirBrakeSpecialCharacteristic" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}CouplingType" minOccurs="0"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;element ref="{http://taf-jsg.info/schemes}BrakeType"/>
 *           &lt;element ref="{http://taf-jsg.info/schemes}BrakeWeight"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numberOfAxles",
    "wagonMaxSpeed",
    "lengthOverBuffers",
    "wagonWeightEmpty",
    "totalLoadWeight",
    "loadingGauge",
    "exceptionalGaugingProfile",
    "exceptionalGaugingIdent",
    "typeOfHeating",
    "handBrake",
    "airBrake",
    "airBrakeSpecialCharacteristic",
    "couplingType",
    "brakeTypeAndBrakeWeight"
})
@XmlRootElement(name = "RollingStockTechnicalData")
public class RollingStockTechnicalData {

    @XmlElement(name = "NumberOfAxles")
    protected Integer numberOfAxles;
    @XmlElement(name = "WagonMaxSpeed")
    protected Integer wagonMaxSpeed;
    @XmlElement(name = "LengthOverBuffers")
    protected Integer lengthOverBuffers;
    @XmlElement(name = "WagonWeightEmpty")
    protected Integer wagonWeightEmpty;
    @XmlElement(name = "TotalLoadWeight")
    protected Integer totalLoadWeight;
    @XmlElement(name = "LoadingGauge")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String loadingGauge;
    @XmlElement(name = "ExceptionalGaugingProfile")
    protected String exceptionalGaugingProfile;
    @XmlElement(name = "ExceptionalGaugingIdent")
    protected ExceptionalGaugingIdent exceptionalGaugingIdent;
    @XmlElement(name = "TypeOfHeating")
    protected String typeOfHeating;
    @XmlElement(name = "HandBrake")
    protected HandBrake handBrake;
    @XmlElement(name = "AirBrake")
    protected AirBrake airBrake;
    @XmlElement(name = "AirBrakeSpecialCharacteristic")
    protected String airBrakeSpecialCharacteristic;
    @XmlElement(name = "CouplingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String couplingType;
    @XmlElementRefs({
        @XmlElementRef(name = "BrakeWeight", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "BrakeType", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> brakeTypeAndBrakeWeight;

    /**
     * Gets the value of the numberOfAxles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfAxles() {
        return numberOfAxles;
    }

    /**
     * Sets the value of the numberOfAxles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfAxles(Integer value) {
        this.numberOfAxles = value;
    }

    /**
     * Gets the value of the wagonMaxSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWagonMaxSpeed() {
        return wagonMaxSpeed;
    }

    /**
     * Sets the value of the wagonMaxSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWagonMaxSpeed(Integer value) {
        this.wagonMaxSpeed = value;
    }

    /**
     * Gets the value of the lengthOverBuffers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLengthOverBuffers() {
        return lengthOverBuffers;
    }

    /**
     * Sets the value of the lengthOverBuffers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLengthOverBuffers(Integer value) {
        this.lengthOverBuffers = value;
    }

    /**
     * Gets the value of the wagonWeightEmpty property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getWagonWeightEmpty() {
        return wagonWeightEmpty;
    }

    /**
     * Sets the value of the wagonWeightEmpty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setWagonWeightEmpty(Integer value) {
        this.wagonWeightEmpty = value;
    }

    /**
     * Gets the value of the totalLoadWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalLoadWeight() {
        return totalLoadWeight;
    }

    /**
     * Sets the value of the totalLoadWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalLoadWeight(Integer value) {
        this.totalLoadWeight = value;
    }

    /**
     * Gets the value of the loadingGauge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLoadingGauge() {
        return loadingGauge;
    }

    /**
     * Sets the value of the loadingGauge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLoadingGauge(String value) {
        this.loadingGauge = value;
    }

    /**
     * Gets the value of the exceptionalGaugingProfile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExceptionalGaugingProfile() {
        return exceptionalGaugingProfile;
    }

    /**
     * Sets the value of the exceptionalGaugingProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExceptionalGaugingProfile(String value) {
        this.exceptionalGaugingProfile = value;
    }

    /**
     * Gets the value of the exceptionalGaugingIdent property.
     * 
     * @return
     *     possible object is
     *     {@link ExceptionalGaugingIdent }
     *     
     */
    public ExceptionalGaugingIdent getExceptionalGaugingIdent() {
        return exceptionalGaugingIdent;
    }

    /**
     * Sets the value of the exceptionalGaugingIdent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExceptionalGaugingIdent }
     *     
     */
    public void setExceptionalGaugingIdent(ExceptionalGaugingIdent value) {
        this.exceptionalGaugingIdent = value;
    }

    /**
     * Gets the value of the typeOfHeating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfHeating() {
        return typeOfHeating;
    }

    /**
     * Sets the value of the typeOfHeating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfHeating(String value) {
        this.typeOfHeating = value;
    }

    /**
     * Gets the value of the handBrake property.
     * 
     * @return
     *     possible object is
     *     {@link HandBrake }
     *     
     */
    public HandBrake getHandBrake() {
        return handBrake;
    }

    /**
     * Sets the value of the handBrake property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandBrake }
     *     
     */
    public void setHandBrake(HandBrake value) {
        this.handBrake = value;
    }

    /**
     * Gets the value of the airBrake property.
     * 
     * @return
     *     possible object is
     *     {@link AirBrake }
     *     
     */
    public AirBrake getAirBrake() {
        return airBrake;
    }

    /**
     * Sets the value of the airBrake property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirBrake }
     *     
     */
    public void setAirBrake(AirBrake value) {
        this.airBrake = value;
    }

    /**
     * Gets the value of the airBrakeSpecialCharacteristic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirBrakeSpecialCharacteristic() {
        return airBrakeSpecialCharacteristic;
    }

    /**
     * Sets the value of the airBrakeSpecialCharacteristic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirBrakeSpecialCharacteristic(String value) {
        this.airBrakeSpecialCharacteristic = value;
    }

    /**
     * Gets the value of the couplingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCouplingType() {
        return couplingType;
    }

    /**
     * Sets the value of the couplingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCouplingType(String value) {
        this.couplingType = value;
    }

    /**
     * Gets the value of the brakeTypeAndBrakeWeight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the brakeTypeAndBrakeWeight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBrakeTypeAndBrakeWeight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getBrakeTypeAndBrakeWeight() {
        if (brakeTypeAndBrakeWeight == null) {
            brakeTypeAndBrakeWeight = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.brakeTypeAndBrakeWeight;
    }

}
