//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://taf-jsg.info/schemes}EuropeanVehicleNumber"/>
 *         &lt;element name="TrainsetID">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "europeanVehicleNumber",
    "trainsetID"
})
@XmlRootElement(name = "RollingStockIdentification")
public class RollingStockIdentification {

    @XmlElement(name = "EuropeanVehicleNumber")
    protected String europeanVehicleNumber;
    @XmlElement(name = "TrainsetID")
    protected String trainsetID;

    /**
     * Gets the value of the europeanVehicleNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEuropeanVehicleNumber() {
        return europeanVehicleNumber;
    }

    /**
     * Sets the value of the europeanVehicleNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEuropeanVehicleNumber(String value) {
        this.europeanVehicleNumber = value;
    }

    /**
     * Gets the value of the trainsetID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainsetID() {
        return trainsetID;
    }

    /**
     * Sets the value of the trainsetID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainsetID(String value) {
        this.trainsetID = value;
    }

}
