//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}VesselIndication"/>
 *         &lt;element name="HarbourName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ShipOwner" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vesselIndication",
    "harbourName",
    "shipOwner"
})
@XmlRootElement(name = "Ship")
public class Ship {

    @XmlElement(name = "VesselIndication", required = true)
    protected VesselIndication vesselIndication;
    @XmlElement(name = "HarbourName")
    protected String harbourName;
    @XmlElement(name = "ShipOwner")
    protected String shipOwner;

    /**
     * Gets the value of the vesselIndication property.
     * 
     * @return
     *     possible object is
     *     {@link VesselIndication }
     *     
     */
    public VesselIndication getVesselIndication() {
        return vesselIndication;
    }

    /**
     * Sets the value of the vesselIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link VesselIndication }
     *     
     */
    public void setVesselIndication(VesselIndication value) {
        this.vesselIndication = value;
    }

    /**
     * Gets the value of the harbourName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarbourName() {
        return harbourName;
    }

    /**
     * Sets the value of the harbourName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarbourName(String value) {
        this.harbourName = value;
    }

    /**
     * Gets the value of the shipOwner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipOwner() {
        return shipOwner;
    }

    /**
     * Sets the value of the shipOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipOwner(String value) {
        this.shipOwner = value;
    }

}
