//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}RU_Partner" minOccurs="0"/>
 *         &lt;element name="SpecialTreatmentCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SpecialTreatmentInformation" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Location" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ruPartner",
    "specialTreatmentCode",
    "specialTreatmentInformation",
    "location"
})
@XmlRootElement(name = "SpecialTreatments")
public class SpecialTreatments {

    @XmlElement(name = "RU_Partner")
    protected Integer ruPartner;
    @XmlElement(name = "SpecialTreatmentCode", required = true)
    protected String specialTreatmentCode;
    @XmlElement(name = "SpecialTreatmentInformation")
    protected String specialTreatmentInformation;
    @XmlElement(name = "Location")
    protected LocationIdent location;

    /**
     * Railway Undertaking dedicated to fulfill the
     * 							special treatment
     * 						
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRUPartner() {
        return ruPartner;
    }

    /**
     * Sets the value of the ruPartner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRUPartner(Integer value) {
        this.ruPartner = value;
    }

    /**
     * Gets the value of the specialTreatmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialTreatmentCode() {
        return specialTreatmentCode;
    }

    /**
     * Sets the value of the specialTreatmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialTreatmentCode(String value) {
        this.specialTreatmentCode = value;
    }

    /**
     * Gets the value of the specialTreatmentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialTreatmentInformation() {
        return specialTreatmentInformation;
    }

    /**
     * Sets the value of the specialTreatmentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialTreatmentInformation(String value) {
        this.specialTreatmentInformation = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setLocation(LocationIdent value) {
        this.location = value;
    }

}
