//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LocoTypeNumber"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TractionMode"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainCC_System" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainRadioSystem" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TractionWeight" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}Length" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locoTypeNumber",
    "tractionMode",
    "trainCCSystem",
    "trainRadioSystem",
    "tractionWeight",
    "length"
})
@XmlRootElement(name = "TractionDetails")
public class TractionDetails {

    @XmlElement(name = "LocoTypeNumber", required = true)
    protected String locoTypeNumber;
    @XmlElement(name = "TractionMode")
    protected int tractionMode;
    @XmlElement(name = "TrainCC_System")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String trainCCSystem;
    @XmlElement(name = "TrainRadioSystem")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String trainRadioSystem;
    @XmlElement(name = "TractionWeight")
    protected Integer tractionWeight;
    @XmlElement(name = "Length")
    protected Length length;

    /**
     * Gets the value of the locoTypeNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocoTypeNumber() {
        return locoTypeNumber;
    }

    /**
     * Sets the value of the locoTypeNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocoTypeNumber(String value) {
        this.locoTypeNumber = value;
    }

    /**
     * Identifies the mode of deployment of a traction
     * 							unit within a train
     * 						
     * 
     */
    public int getTractionMode() {
        return tractionMode;
    }

    /**
     * Sets the value of the tractionMode property.
     * 
     */
    public void setTractionMode(int value) {
        this.tractionMode = value;
    }

    /**
     * Gets the value of the trainCCSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainCCSystem() {
        return trainCCSystem;
    }

    /**
     * Sets the value of the trainCCSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainCCSystem(String value) {
        this.trainCCSystem = value;
    }

    /**
     * Gets the value of the trainRadioSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainRadioSystem() {
        return trainRadioSystem;
    }

    /**
     * Sets the value of the trainRadioSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainRadioSystem(String value) {
        this.trainRadioSystem = value;
    }

    /**
     * Check with group to see if it is for sum or
     * 							individual - check TAP
     * 						
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTractionWeight() {
        return tractionWeight;
    }

    /**
     * Sets the value of the tractionWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTractionWeight(Integer value) {
        this.tractionWeight = value;
    }

    /**
     * Length in milimetres - Used for TAP
     * 						
     * 
     * @return
     *     possible object is
     *     {@link Length }
     *     
     */
    public Length getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Length }
     *     
     */
    public void setLength(Length value) {
        this.length = value;
    }

}
