//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainType"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainWeight"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainLength"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainCC_System" maxOccurs="9" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainRadioSystem" maxOccurs="9" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainMaxSpeed" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MaxAxleWeight" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}BrakeType" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}BrakeWeight" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}NumberOfVehicles" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}NumberOfAxles" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trainType",
    "trainWeight",
    "trainLength",
    "trainCCSystem",
    "trainRadioSystem",
    "trainMaxSpeed",
    "maxAxleWeight",
    "brakeType",
    "brakeWeight",
    "numberOfVehicles",
    "numberOfAxles"
})
@XmlRootElement(name = "TrainRunningTechData")
public class TrainRunningTechData {

    @XmlElement(name = "TrainType", required = true)
    protected BigInteger trainType;
    @XmlElement(name = "TrainWeight")
    protected int trainWeight;
    @XmlElement(name = "TrainLength")
    protected int trainLength;
    @XmlElement(name = "TrainCC_System")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> trainCCSystem;
    @XmlElement(name = "TrainRadioSystem")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected List<String> trainRadioSystem;
    @XmlElement(name = "TrainMaxSpeed")
    protected Integer trainMaxSpeed;
    @XmlElement(name = "MaxAxleWeight")
    protected BigDecimal maxAxleWeight;
    @XmlElement(name = "BrakeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String brakeType;
    @XmlElement(name = "BrakeWeight")
    protected Integer brakeWeight;
    @XmlElement(name = "NumberOfVehicles")
    protected Integer numberOfVehicles;
    @XmlElement(name = "NumberOfAxles")
    protected Integer numberOfAxles;

    /**
     * Gets the value of the trainType property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrainType() {
        return trainType;
    }

    /**
     * Sets the value of the trainType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrainType(BigInteger value) {
        this.trainType = value;
    }

    /**
     * Gets the value of the trainWeight property.
     * 
     */
    public int getTrainWeight() {
        return trainWeight;
    }

    /**
     * Sets the value of the trainWeight property.
     * 
     */
    public void setTrainWeight(int value) {
        this.trainWeight = value;
    }

    /**
     * Gets the value of the trainLength property.
     * 
     */
    public int getTrainLength() {
        return trainLength;
    }

    /**
     * Sets the value of the trainLength property.
     * 
     */
    public void setTrainLength(int value) {
        this.trainLength = value;
    }

    /**
     * Gets the value of the trainCCSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainCCSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainCCSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTrainCCSystem() {
        if (trainCCSystem == null) {
            trainCCSystem = new ArrayList<String>();
        }
        return this.trainCCSystem;
    }

    /**
     * Gets the value of the trainRadioSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trainRadioSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrainRadioSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTrainRadioSystem() {
        if (trainRadioSystem == null) {
            trainRadioSystem = new ArrayList<String>();
        }
        return this.trainRadioSystem;
    }

    /**
     * Gets the value of the trainMaxSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTrainMaxSpeed() {
        return trainMaxSpeed;
    }

    /**
     * Sets the value of the trainMaxSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTrainMaxSpeed(Integer value) {
        this.trainMaxSpeed = value;
    }

    /**
     * Gets the value of the maxAxleWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaxAxleWeight() {
        return maxAxleWeight;
    }

    /**
     * Sets the value of the maxAxleWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaxAxleWeight(BigDecimal value) {
        this.maxAxleWeight = value;
    }

    /**
     * Gets the value of the brakeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrakeType() {
        return brakeType;
    }

    /**
     * Sets the value of the brakeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrakeType(String value) {
        this.brakeType = value;
    }

    /**
     * Gets the value of the brakeWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBrakeWeight() {
        return brakeWeight;
    }

    /**
     * Sets the value of the brakeWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBrakeWeight(Integer value) {
        this.brakeWeight = value;
    }

    /**
     * Gets the value of the numberOfVehicles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfVehicles() {
        return numberOfVehicles;
    }

    /**
     * Sets the value of the numberOfVehicles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfVehicles(Integer value) {
        this.numberOfVehicles = value;
    }

    /**
     * Gets the value of the numberOfAxles property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfAxles() {
        return numberOfAxles;
    }

    /**
     * Sets the value of the numberOfAxles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfAxles(Integer value) {
        this.numberOfAxles = value;
    }

}
