//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageHeader"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageStatus"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TransportOperationalIdentifiers" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}OperationalTrainNumberIdentifier"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ReferenceOTN" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ResponsibleRU" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainContactDetails" minOccurs="0"/>
 *         &lt;element name="TrainLocation" type="{http://taf-jsg.info/schemes}LocationIdent" minOccurs="0"/>
 *         &lt;element name="TrainReadyStatus" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TrainReady">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;enumeration value="0"/>
 *                         &lt;enumeration value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}TrainDelay" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}DelayCause" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TransferPoint" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TransfereeIM" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainStartTime" minOccurs="0"/>
 *         &lt;element name="TrainReadyTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeader",
    "messageStatus",
    "transportOperationalIdentifiers",
    "operationalTrainNumberIdentifier",
    "referenceOTN",
    "responsibleRU",
    "trainContactDetails",
    "trainLocation",
    "trainReadyStatus",
    "transferPoint",
    "transfereeIM",
    "trainStartTime",
    "trainReadyTime"
})
@XmlRootElement(name = "TrainReadyMessage")
public class TrainReadyMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeader messageHeader;
    @XmlElement(name = "MessageStatus", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String messageStatus;
    @XmlElement(name = "TransportOperationalIdentifiers")
    protected List<TransportOperationalIdentifiers> transportOperationalIdentifiers;
    @XmlElement(name = "OperationalTrainNumberIdentifier", required = true)
    protected OperationalTrainNumberIdentifier operationalTrainNumberIdentifier;
    @XmlElement(name = "ReferenceOTN")
    protected ReferenceOTN referenceOTN;
    @XmlElement(name = "ResponsibleRU")
    protected Integer responsibleRU;
    @XmlElement(name = "TrainContactDetails")
    protected String trainContactDetails;
    @XmlElement(name = "TrainLocation")
    protected LocationIdent trainLocation;
    @XmlElement(name = "TrainReadyStatus")
    protected TrainReadyMessage.TrainReadyStatus trainReadyStatus;
    @XmlElement(name = "TransferPoint")
    protected LocationIdent transferPoint;
    @XmlElement(name = "TransfereeIM")
    protected Integer transfereeIM;
    @XmlElement(name = "TrainStartTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar trainStartTime;
    @XmlElement(name = "TrainReadyTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar trainReadyTime;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the messageStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageStatus() {
        return messageStatus;
    }

    /**
     * Sets the value of the messageStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageStatus(String value) {
        this.messageStatus = value;
    }

    /**
     * Gets the value of the transportOperationalIdentifiers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transportOperationalIdentifiers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransportOperationalIdentifiers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransportOperationalIdentifiers }
     * 
     * 
     */
    public List<TransportOperationalIdentifiers> getTransportOperationalIdentifiers() {
        if (transportOperationalIdentifiers == null) {
            transportOperationalIdentifiers = new ArrayList<TransportOperationalIdentifiers>();
        }
        return this.transportOperationalIdentifiers;
    }

    /**
     * Gets the value of the operationalTrainNumberIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalTrainNumberIdentifier }
     *     
     */
    public OperationalTrainNumberIdentifier getOperationalTrainNumberIdentifier() {
        return operationalTrainNumberIdentifier;
    }

    /**
     * Sets the value of the operationalTrainNumberIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalTrainNumberIdentifier }
     *     
     */
    public void setOperationalTrainNumberIdentifier(OperationalTrainNumberIdentifier value) {
        this.operationalTrainNumberIdentifier = value;
    }

    /**
     * Gets the value of the referenceOTN property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceOTN }
     *     
     */
    public ReferenceOTN getReferenceOTN() {
        return referenceOTN;
    }

    /**
     * Sets the value of the referenceOTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceOTN }
     *     
     */
    public void setReferenceOTN(ReferenceOTN value) {
        this.referenceOTN = value;
    }

    /**
     * Gets the value of the responsibleRU property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getResponsibleRU() {
        return responsibleRU;
    }

    /**
     * Sets the value of the responsibleRU property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setResponsibleRU(Integer value) {
        this.responsibleRU = value;
    }

    /**
     * Gets the value of the trainContactDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainContactDetails() {
        return trainContactDetails;
    }

    /**
     * Sets the value of the trainContactDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainContactDetails(String value) {
        this.trainContactDetails = value;
    }

    /**
     * Gets the value of the trainLocation property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getTrainLocation() {
        return trainLocation;
    }

    /**
     * Sets the value of the trainLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setTrainLocation(LocationIdent value) {
        this.trainLocation = value;
    }

    /**
     * Gets the value of the trainReadyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TrainReadyMessage.TrainReadyStatus }
     *     
     */
    public TrainReadyMessage.TrainReadyStatus getTrainReadyStatus() {
        return trainReadyStatus;
    }

    /**
     * Sets the value of the trainReadyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainReadyMessage.TrainReadyStatus }
     *     
     */
    public void setTrainReadyStatus(TrainReadyMessage.TrainReadyStatus value) {
        this.trainReadyStatus = value;
    }

    /**
     * Transfer point or station of destination in the
     * 							considered network where the Reference Train Numbers refers to
     * 						
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getTransferPoint() {
        return transferPoint;
    }

    /**
     * Sets the value of the transferPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setTransferPoint(LocationIdent value) {
        this.transferPoint = value;
    }

    /**
     * Gets the value of the transfereeIM property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTransfereeIM() {
        return transfereeIM;
    }

    /**
     * Sets the value of the transfereeIM property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTransfereeIM(Integer value) {
        this.transfereeIM = value;
    }

    /**
     * Gets the value of the trainStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrainStartTime() {
        return trainStartTime;
    }

    /**
     * Sets the value of the trainStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrainStartTime(XMLGregorianCalendar value) {
        this.trainStartTime = value;
    }

    /**
     * Gets the value of the trainReadyTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTrainReadyTime() {
        return trainReadyTime;
    }

    /**
     * Sets the value of the trainReadyTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTrainReadyTime(XMLGregorianCalendar value) {
        this.trainReadyTime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TrainReady">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;enumeration value="0"/>
     *               &lt;enumeration value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{http://taf-jsg.info/schemes}TrainDelay" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}DelayCause" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "trainReady",
        "trainDelay",
        "delayCause"
    })
    public static class TrainReadyStatus {

        @XmlElement(name = "TrainReady", required = true)
        protected BigInteger trainReady;
        @XmlElement(name = "TrainDelay")
        protected TrainDelay trainDelay;
        @XmlElement(name = "DelayCause")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String delayCause;

        /**
         * Gets the value of the trainReady property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getTrainReady() {
            return trainReady;
        }

        /**
         * Sets the value of the trainReady property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setTrainReady(BigInteger value) {
            this.trainReady = value;
        }

        /**
         * Gets the value of the trainDelay property.
         * 
         * @return
         *     possible object is
         *     {@link TrainDelay }
         *     
         */
        public TrainDelay getTrainDelay() {
            return trainDelay;
        }

        /**
         * Sets the value of the trainDelay property.
         * 
         * @param value
         *     allowed object is
         *     {@link TrainDelay }
         *     
         */
        public void setTrainDelay(TrainDelay value) {
            this.trainDelay = value;
        }

        /**
         * Gets the value of the delayCause property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDelayCause() {
            return delayCause;
        }

        /**
         * Sets the value of the delayCause property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDelayCause(String value) {
            this.delayCause = value;
        }

    }

}
