//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrainDescriptionManner">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Count" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="DirectionOfDescription">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VehicleList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="VehicleTrainPosition" maxOccurs="unbounded">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;minInclusive value="1"/>
 *                         &lt;maxInclusive value="99"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;choice>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}RollingStockIdentification"/>
 *                     &lt;element name="RollingStockType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/choice>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}TractionType" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}TractionMode" minOccurs="0"/>
 *                   &lt;element name="PoweredLocomotiveOrTrainset" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}DriverIndication" minOccurs="0"/>
 *                   &lt;element name="TrainsetOrientation" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *                         &lt;enumeration value="1"/>
 *                         &lt;enumeration value="2"/>
 *                         &lt;enumeration value="9"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="KeeperShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}RollingStockTechnicalData" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}TechnicalPassengerRollingStockRestriction" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}ItineraryOfRollingStock" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}InternalVehicleFacility" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}CharacteristicDescriptionCode" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}FacilityTypeDescriptionCode" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}CommercialService" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}SpecialServiceDescription" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}InformationToBeDisplayed" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}CoachOrTrainsetCommercialData" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}FreeTextField" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}Parameters" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trainDescriptionManner",
    "count",
    "directionOfDescription",
    "vehicleList"
})
@XmlRootElement(name = "TrainCompositionPassenger")
public class TrainCompositionPassenger {

    @XmlElement(name = "TrainDescriptionManner", required = true)
    protected BigInteger trainDescriptionManner;
    @XmlElement(name = "Count")
    protected BigInteger count;
    @XmlElement(name = "DirectionOfDescription", required = true)
    protected BigInteger directionOfDescription;
    @XmlElement(name = "VehicleList", required = true)
    protected TrainCompositionPassenger.VehicleList vehicleList;

    /**
     * Gets the value of the trainDescriptionManner property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTrainDescriptionManner() {
        return trainDescriptionManner;
    }

    /**
     * Sets the value of the trainDescriptionManner property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTrainDescriptionManner(BigInteger value) {
        this.trainDescriptionManner = value;
    }

    /**
     * Gets the value of the count property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCount(BigInteger value) {
        this.count = value;
    }

    /**
     * Gets the value of the directionOfDescription property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDirectionOfDescription() {
        return directionOfDescription;
    }

    /**
     * Sets the value of the directionOfDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDirectionOfDescription(BigInteger value) {
        this.directionOfDescription = value;
    }

    /**
     * Gets the value of the vehicleList property.
     * 
     * @return
     *     possible object is
     *     {@link TrainCompositionPassenger.VehicleList }
     *     
     */
    public TrainCompositionPassenger.VehicleList getVehicleList() {
        return vehicleList;
    }

    /**
     * Sets the value of the vehicleList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainCompositionPassenger.VehicleList }
     *     
     */
    public void setVehicleList(TrainCompositionPassenger.VehicleList value) {
        this.vehicleList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="VehicleTrainPosition" maxOccurs="unbounded">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;minInclusive value="1"/>
     *               &lt;maxInclusive value="99"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;choice>
     *           &lt;element ref="{http://taf-jsg.info/schemes}RollingStockIdentification"/>
     *           &lt;element name="RollingStockType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;/choice>
     *         &lt;element ref="{http://taf-jsg.info/schemes}TractionType" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}TractionMode" minOccurs="0"/>
     *         &lt;element name="PoweredLocomotiveOrTrainset" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}DriverIndication" minOccurs="0"/>
     *         &lt;element name="TrainsetOrientation" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
     *               &lt;enumeration value="1"/>
     *               &lt;enumeration value="2"/>
     *               &lt;enumeration value="9"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="KeeperShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}RollingStockTechnicalData" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}TechnicalPassengerRollingStockRestriction" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}ItineraryOfRollingStock" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}InternalVehicleFacility" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}CharacteristicDescriptionCode" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}FacilityTypeDescriptionCode" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}CommercialService" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}SpecialServiceDescription" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}InformationToBeDisplayed" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}CoachOrTrainsetCommercialData" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}FreeTextField" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}Parameters" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "vehicleTrainPositionAndRollingStockIdentificationOrRollingStockType"
    })
    public static class VehicleList {

        @XmlElementRefs({
            @XmlElementRef(name = "TractionType", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "TractionMode", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "ItineraryOfRollingStock", namespace = "http://taf-jsg.info/schemes", type = ItineraryOfRollingStock.class),
            @XmlElementRef(name = "KeeperShortName", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "PoweredLocomotiveOrTrainset", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "InternalVehicleFacility", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "TechnicalPassengerRollingStockRestriction", namespace = "http://taf-jsg.info/schemes", type = TechnicalPassengerRollingStockRestriction.class),
            @XmlElementRef(name = "InformationToBeDisplayed", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "VehicleTrainPosition", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "RollingStockTechnicalData", namespace = "http://taf-jsg.info/schemes", type = RollingStockTechnicalData.class),
            @XmlElementRef(name = "CommercialService", namespace = "http://taf-jsg.info/schemes", type = CommercialService.class),
            @XmlElementRef(name = "SpecialServiceDescription", namespace = "http://taf-jsg.info/schemes", type = SpecialServiceDescription.class),
            @XmlElementRef(name = "TrainsetOrientation", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "FreeTextField", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "CharacteristicDescriptionCode", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "FacilityTypeDescriptionCode", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "RollingStockIdentification", namespace = "http://taf-jsg.info/schemes", type = RollingStockIdentification.class),
            @XmlElementRef(name = "RollingStockType", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "Parameters", namespace = "http://taf-jsg.info/schemes", type = Parameters.class),
            @XmlElementRef(name = "DriverIndication", namespace = "http://taf-jsg.info/schemes", type = JAXBElement.class),
            @XmlElementRef(name = "CoachOrTrainsetCommercialData", namespace = "http://taf-jsg.info/schemes", type = CoachOrTrainsetCommercialData.class)
        })
        protected List<Object> vehicleTrainPositionAndRollingStockIdentificationOrRollingStockType;

        /**
         * Gets the value of the vehicleTrainPositionAndRollingStockIdentificationOrRollingStockType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the vehicleTrainPositionAndRollingStockIdentificationOrRollingStockType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVehicleTrainPositionAndRollingStockIdentificationOrRollingStockType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link Integer }{@code >}
         * {@link ItineraryOfRollingStock }
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link TechnicalPassengerRollingStockRestriction }
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link Integer }{@code >}
         * {@link RollingStockTechnicalData }
         * {@link CommercialService }
         * {@link SpecialServiceDescription }
         * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         * {@link RollingStockIdentification }
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link Parameters }
         * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
         * {@link CoachOrTrainsetCommercialData }
         * 
         * 
         */
        public List<Object> getVehicleTrainPositionAndRollingStockIdentificationOrRollingStockType() {
            if (vehicleTrainPositionAndRollingStockIdentificationOrRollingStockType == null) {
                vehicleTrainPositionAndRollingStockIdentificationOrRollingStockType = new ArrayList<Object>();
            }
            return this.vehicleTrainPositionAndRollingStockIdentificationOrRollingStockType;
        }

    }

}
