//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}PassengerJourneySectionOrigin"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}JourneySectionDestination"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ResponsibilityActualSectionPassenger"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}ResponsibilityNextSectionPassenger" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainDataPassenger" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainCompositionPassenger"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "passengerJourneySectionOrigin",
    "journeySectionDestination",
    "responsibilityActualSectionPassenger",
    "responsibilityNextSectionPassenger",
    "trainDataPassenger",
    "trainCompositionPassenger"
})
@XmlRootElement(name = "TrainCompositionJourneySectionPassenger")
public class TrainCompositionJourneySectionPassenger {

    @XmlElement(name = "PassengerJourneySectionOrigin", required = true)
    protected PassengerJourneySectionOrigin passengerJourneySectionOrigin;
    @XmlElement(name = "JourneySectionDestination", required = true)
    protected LocationIdent journeySectionDestination;
    @XmlElement(name = "ResponsibilityActualSectionPassenger", required = true)
    protected ResponsibilityActualSectionPassenger responsibilityActualSectionPassenger;
    @XmlElement(name = "ResponsibilityNextSectionPassenger")
    protected ResponsibilityNextSectionPassenger responsibilityNextSectionPassenger;
    @XmlElement(name = "TrainDataPassenger")
    protected TrainDataPassenger trainDataPassenger;
    @XmlElement(name = "TrainCompositionPassenger", required = true)
    protected TrainCompositionPassenger trainCompositionPassenger;

    /**
     * Gets the value of the passengerJourneySectionOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link PassengerJourneySectionOrigin }
     *     
     */
    public PassengerJourneySectionOrigin getPassengerJourneySectionOrigin() {
        return passengerJourneySectionOrigin;
    }

    /**
     * Sets the value of the passengerJourneySectionOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassengerJourneySectionOrigin }
     *     
     */
    public void setPassengerJourneySectionOrigin(PassengerJourneySectionOrigin value) {
        this.passengerJourneySectionOrigin = value;
    }

    /**
     * Gets the value of the journeySectionDestination property.
     * 
     * @return
     *     possible object is
     *     {@link LocationIdent }
     *     
     */
    public LocationIdent getJourneySectionDestination() {
        return journeySectionDestination;
    }

    /**
     * Sets the value of the journeySectionDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationIdent }
     *     
     */
    public void setJourneySectionDestination(LocationIdent value) {
        this.journeySectionDestination = value;
    }

    /**
     * Gets the value of the responsibilityActualSectionPassenger property.
     * 
     * @return
     *     possible object is
     *     {@link ResponsibilityActualSectionPassenger }
     *     
     */
    public ResponsibilityActualSectionPassenger getResponsibilityActualSectionPassenger() {
        return responsibilityActualSectionPassenger;
    }

    /**
     * Sets the value of the responsibilityActualSectionPassenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponsibilityActualSectionPassenger }
     *     
     */
    public void setResponsibilityActualSectionPassenger(ResponsibilityActualSectionPassenger value) {
        this.responsibilityActualSectionPassenger = value;
    }

    /**
     * Gets the value of the responsibilityNextSectionPassenger property.
     * 
     * @return
     *     possible object is
     *     {@link ResponsibilityNextSectionPassenger }
     *     
     */
    public ResponsibilityNextSectionPassenger getResponsibilityNextSectionPassenger() {
        return responsibilityNextSectionPassenger;
    }

    /**
     * Sets the value of the responsibilityNextSectionPassenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponsibilityNextSectionPassenger }
     *     
     */
    public void setResponsibilityNextSectionPassenger(ResponsibilityNextSectionPassenger value) {
        this.responsibilityNextSectionPassenger = value;
    }

    /**
     * Gets the value of the trainDataPassenger property.
     * 
     * @return
     *     possible object is
     *     {@link TrainDataPassenger }
     *     
     */
    public TrainDataPassenger getTrainDataPassenger() {
        return trainDataPassenger;
    }

    /**
     * Sets the value of the trainDataPassenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainDataPassenger }
     *     
     */
    public void setTrainDataPassenger(TrainDataPassenger value) {
        this.trainDataPassenger = value;
    }

    /**
     * Gets the value of the trainCompositionPassenger property.
     * 
     * @return
     *     possible object is
     *     {@link TrainCompositionPassenger }
     *     
     */
    public TrainCompositionPassenger getTrainCompositionPassenger() {
        return trainCompositionPassenger;
    }

    /**
     * Sets the value of the trainCompositionPassenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrainCompositionPassenger }
     *     
     */
    public void setTrainCompositionPassenger(TrainCompositionPassenger value) {
        this.trainCompositionPassenger = value;
    }

}
