//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}LengthOverBuffers"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberOfAxles"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}AirBrakeType" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}BrakingPowerVariationDevice" minOccurs="0"/>
 *         &lt;element name="AirBrakeSpecialCharacteristic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="0"/>
 *               &lt;maxInclusive value="9"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}HandBrakeType" minOccurs="0"/>
 *         &lt;element name="HandBrakeBrakedWeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="000"/>
 *               &lt;maxInclusive value="999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}NormalLoadingGauge" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonWeightEmpty"/>
 *         &lt;element name="TechnicalRestrictions" type="{http://taf-jsg.info/schemes}Numeric2-2" maxOccurs="6" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "lengthOverBuffers",
    "wagonNumberOfAxles",
    "airBrakeType",
    "brakingPowerVariationDevice",
    "airBrakeSpecialCharacteristic",
    "handBrakeType",
    "handBrakeBrakedWeight",
    "normalLoadingGauge",
    "wagonWeightEmpty",
    "technicalRestrictions"
})
@XmlRootElement(name = "WagonTechData")
public class WagonTechData {

    @XmlElement(name = "LengthOverBuffers")
    protected int lengthOverBuffers;
    @XmlElement(name = "WagonNumberOfAxles")
    protected int wagonNumberOfAxles;
    @XmlElement(name = "AirBrakeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String airBrakeType;
    @XmlElement(name = "BrakingPowerVariationDevice")
    protected BigInteger brakingPowerVariationDevice;
    @XmlElement(name = "AirBrakeSpecialCharacteristic")
    protected Integer airBrakeSpecialCharacteristic;
    @XmlElement(name = "HandBrakeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String handBrakeType;
    @XmlElement(name = "HandBrakeBrakedWeight")
    protected Integer handBrakeBrakedWeight;
    @XmlElement(name = "NormalLoadingGauge")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String normalLoadingGauge;
    @XmlElement(name = "WagonWeightEmpty")
    protected int wagonWeightEmpty;
    @XmlElement(name = "TechnicalRestrictions", type = Integer.class)
    protected List<Integer> technicalRestrictions;

    /**
     * Gets the value of the lengthOverBuffers property.
     * 
     */
    public int getLengthOverBuffers() {
        return lengthOverBuffers;
    }

    /**
     * Sets the value of the lengthOverBuffers property.
     * 
     */
    public void setLengthOverBuffers(int value) {
        this.lengthOverBuffers = value;
    }

    /**
     * Gets the value of the wagonNumberOfAxles property.
     * 
     */
    public int getWagonNumberOfAxles() {
        return wagonNumberOfAxles;
    }

    /**
     * Sets the value of the wagonNumberOfAxles property.
     * 
     */
    public void setWagonNumberOfAxles(int value) {
        this.wagonNumberOfAxles = value;
    }

    /**
     * Gets the value of the airBrakeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirBrakeType() {
        return airBrakeType;
    }

    /**
     * Sets the value of the airBrakeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirBrakeType(String value) {
        this.airBrakeType = value;
    }

    /**
     * Gets the value of the brakingPowerVariationDevice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBrakingPowerVariationDevice() {
        return brakingPowerVariationDevice;
    }

    /**
     * Sets the value of the brakingPowerVariationDevice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBrakingPowerVariationDevice(BigInteger value) {
        this.brakingPowerVariationDevice = value;
    }

    /**
     * Gets the value of the airBrakeSpecialCharacteristic property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAirBrakeSpecialCharacteristic() {
        return airBrakeSpecialCharacteristic;
    }

    /**
     * Sets the value of the airBrakeSpecialCharacteristic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAirBrakeSpecialCharacteristic(Integer value) {
        this.airBrakeSpecialCharacteristic = value;
    }

    /**
     * Gets the value of the handBrakeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandBrakeType() {
        return handBrakeType;
    }

    /**
     * Sets the value of the handBrakeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandBrakeType(String value) {
        this.handBrakeType = value;
    }

    /**
     * Gets the value of the handBrakeBrakedWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getHandBrakeBrakedWeight() {
        return handBrakeBrakedWeight;
    }

    /**
     * Sets the value of the handBrakeBrakedWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHandBrakeBrakedWeight(Integer value) {
        this.handBrakeBrakedWeight = value;
    }

    /**
     * Gets the value of the normalLoadingGauge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNormalLoadingGauge() {
        return normalLoadingGauge;
    }

    /**
     * Sets the value of the normalLoadingGauge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNormalLoadingGauge(String value) {
        this.normalLoadingGauge = value;
    }

    /**
     * Gets the value of the wagonWeightEmpty property.
     * 
     */
    public int getWagonWeightEmpty() {
        return wagonWeightEmpty;
    }

    /**
     * Sets the value of the wagonWeightEmpty property.
     * 
     */
    public void setWagonWeightEmpty(int value) {
        this.wagonWeightEmpty = value;
    }

    /**
     * Gets the value of the technicalRestrictions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the technicalRestrictions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTechnicalRestrictions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getTechnicalRestrictions() {
        if (technicalRestrictions == null) {
            technicalRestrictions = new ArrayList<Integer>();
        }
        return this.technicalRestrictions;
    }

}
