//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberFreight"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonTrainPosition"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonOperationalData"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonTechData"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wagonNumberFreight",
    "wagonTrainPosition",
    "wagonOperationalData",
    "wagonTechData"
})
@XmlRootElement(name = "WagonData")
public class WagonData {

    @XmlElement(name = "WagonNumberFreight", required = true)
    protected String wagonNumberFreight;
    @XmlElement(name = "WagonTrainPosition")
    protected int wagonTrainPosition;
    @XmlElement(name = "WagonOperationalData", required = true)
    protected WagonOperationalData wagonOperationalData;
    @XmlElement(name = "WagonTechData", required = true)
    protected WagonTechData wagonTechData;

    /**
     * Gets the value of the wagonNumberFreight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWagonNumberFreight() {
        return wagonNumberFreight;
    }

    /**
     * Sets the value of the wagonNumberFreight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWagonNumberFreight(String value) {
        this.wagonNumberFreight = value;
    }

    /**
     * Gets the value of the wagonTrainPosition property.
     * 
     */
    public int getWagonTrainPosition() {
        return wagonTrainPosition;
    }

    /**
     * Sets the value of the wagonTrainPosition property.
     * 
     */
    public void setWagonTrainPosition(int value) {
        this.wagonTrainPosition = value;
    }

    /**
     * Gets the value of the wagonOperationalData property.
     * 
     * @return
     *     possible object is
     *     {@link WagonOperationalData }
     *     
     */
    public WagonOperationalData getWagonOperationalData() {
        return wagonOperationalData;
    }

    /**
     * Sets the value of the wagonOperationalData property.
     * 
     * @param value
     *     allowed object is
     *     {@link WagonOperationalData }
     *     
     */
    public void setWagonOperationalData(WagonOperationalData value) {
        this.wagonOperationalData = value;
    }

    /**
     * Gets the value of the wagonTechData property.
     * 
     * @return
     *     possible object is
     *     {@link WagonTechData }
     *     
     */
    public WagonTechData getWagonTechData() {
        return wagonTechData;
    }

    /**
     * Sets the value of the wagonTechData property.
     * 
     * @param value
     *     allowed object is
     *     {@link WagonTechData }
     *     
     */
    public void setWagonTechData(WagonTechData value) {
        this.wagonTechData = value;
    }

}
