//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}MessageHeader"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonInformation"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}DeliveryInterchangePoint"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}DangerousGoodsIndication" minOccurs="0"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}OperationalTrainNumber"/>
 *         &lt;element ref="{http://taf-jsg.info/schemes}TrainID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageHeader",
    "wagonInformation",
    "deliveryInterchangePoint",
    "dangerousGoodsIndication",
    "operationalTrainNumber",
    "trainID"
})
@XmlRootElement(name = "WagonInterchangeNoticeMessage")
public class WagonInterchangeNoticeMessage {

    @XmlElement(name = "MessageHeader", required = true)
    protected MessageHeader messageHeader;
    @XmlElement(name = "WagonInformation", required = true)
    protected WagonInformation wagonInformation;
    @XmlElement(name = "DeliveryInterchangePoint", required = true)
    protected DeliveryInterchangePoint deliveryInterchangePoint;
    @XmlElement(name = "DangerousGoodsIndication")
    protected DanGoodsType dangerousGoodsIndication;
    @XmlElement(name = "OperationalTrainNumber", required = true)
    protected String operationalTrainNumber;
    @XmlElement(name = "TrainID")
    protected CompositIdentifierOperationalType trainID;

    /**
     * Gets the value of the messageHeader property.
     * 
     * @return
     *     possible object is
     *     {@link MessageHeader }
     *     
     */
    public MessageHeader getMessageHeader() {
        return messageHeader;
    }

    /**
     * Sets the value of the messageHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageHeader }
     *     
     */
    public void setMessageHeader(MessageHeader value) {
        this.messageHeader = value;
    }

    /**
     * Gets the value of the wagonInformation property.
     * 
     * @return
     *     possible object is
     *     {@link WagonInformation }
     *     
     */
    public WagonInformation getWagonInformation() {
        return wagonInformation;
    }

    /**
     * Sets the value of the wagonInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link WagonInformation }
     *     
     */
    public void setWagonInformation(WagonInformation value) {
        this.wagonInformation = value;
    }

    /**
     * Gets the value of the deliveryInterchangePoint property.
     * 
     * @return
     *     possible object is
     *     {@link DeliveryInterchangePoint }
     *     
     */
    public DeliveryInterchangePoint getDeliveryInterchangePoint() {
        return deliveryInterchangePoint;
    }

    /**
     * Sets the value of the deliveryInterchangePoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeliveryInterchangePoint }
     *     
     */
    public void setDeliveryInterchangePoint(DeliveryInterchangePoint value) {
        this.deliveryInterchangePoint = value;
    }

    /**
     * Gets the value of the dangerousGoodsIndication property.
     * 
     * @return
     *     possible object is
     *     {@link DanGoodsType }
     *     
     */
    public DanGoodsType getDangerousGoodsIndication() {
        return dangerousGoodsIndication;
    }

    /**
     * Sets the value of the dangerousGoodsIndication property.
     * 
     * @param value
     *     allowed object is
     *     {@link DanGoodsType }
     *     
     */
    public void setDangerousGoodsIndication(DanGoodsType value) {
        this.dangerousGoodsIndication = value;
    }

    /**
     * Gets the value of the operationalTrainNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationalTrainNumber() {
        return operationalTrainNumber;
    }

    /**
     * Sets the value of the operationalTrainNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationalTrainNumber(String value) {
        this.operationalTrainNumber = value;
    }

    /**
     * Gets the value of the trainID property.
     * 
     * @return
     *     possible object is
     *     {@link CompositIdentifierOperationalType }
     *     
     */
    public CompositIdentifierOperationalType getTrainID() {
        return trainID;
    }

    /**
     * Sets the value of the trainID property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositIdentifierOperationalType }
     *     
     */
    public void setTrainID(CompositIdentifierOperationalType value) {
        this.trainID = value;
    }

}
