//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberFreight"/>
 *         &lt;sequence>
 *           &lt;element name="WagonDetails">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}LoadingStatus"/>
 *                     &lt;element name="WagonInfo" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                           &lt;maxLength value="500"/>
 *                           &lt;minLength value="1"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element name="WagonTypeDetails" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://taf-jsg.info/schemes}WagonWeightEmpty"/>
 *                               &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberOfAxles"/>
 *                               &lt;element ref="{http://taf-jsg.info/schemes}WagonLength"/>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}TotalWeight" minOccurs="0"/>
 *                     &lt;element name="LoadLimit" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                           &lt;minInclusive value="0"/>
 *                           &lt;totalDigits value="4"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}Seals" minOccurs="0"/>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}Ship" minOccurs="0"/>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}DeliveryReference" minOccurs="0"/>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}OriginCountry" minOccurs="0"/>
 *                     &lt;element name="ExceptionalConsignment" maxOccurs="10" minOccurs="0">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;sequence>
 *                               &lt;element ref="{http://taf-jsg.info/schemes}IM_Partner"/>
 *                               &lt;element name="PermissionNumber">
 *                                 &lt;simpleType>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                     &lt;minLength value="1"/>
 *                                     &lt;maxLength value="24"/>
 *                                   &lt;/restriction>
 *                                 &lt;/simpleType>
 *                               &lt;/element>
 *                             &lt;/sequence>
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="ShuntingModalLabel" minOccurs="0">
 *                       &lt;simpleType>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                           &lt;enumeration value="13"/>
 *                           &lt;enumeration value="15"/>
 *                         &lt;/restriction>
 *                       &lt;/simpleType>
 *                     &lt;/element>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}ReferenceNumbers" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *           &lt;element ref="{http://taf-jsg.info/schemes}SummaryOFGoodsWithSameRID" maxOccurs="25" minOccurs="0"/>
 *           &lt;choice>
 *             &lt;sequence>
 *               &lt;element ref="{http://taf-jsg.info/schemes}LoadingTackles" maxOccurs="99" minOccurs="0"/>
 *               &lt;element ref="{http://taf-jsg.info/schemes}Goods" maxOccurs="99"/>
 *             &lt;/sequence>
 *             &lt;element ref="{http://taf-jsg.info/schemes}ITU" maxOccurs="25"/>
 *             &lt;element ref="{http://taf-jsg.info/schemes}RollingRoadUnit" maxOccurs="5"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wagonNumberFreight",
    "wagonDetails",
    "summaryOFGoodsWithSameRID",
    "loadingTackles",
    "goods",
    "itu",
    "rollingRoadUnit"
})
@XmlRootElement(name = "Wagons")
public class Wagons {

    @XmlElement(name = "WagonNumberFreight", required = true)
    protected String wagonNumberFreight;
    @XmlElement(name = "WagonDetails", required = true)
    protected Wagons.WagonDetails wagonDetails;
    @XmlElement(name = "SummaryOFGoodsWithSameRID")
    protected List<SummaryOFGoodsWithSameRID> summaryOFGoodsWithSameRID;
    @XmlElement(name = "LoadingTackles")
    protected List<LoadingTackles> loadingTackles;
    @XmlElement(name = "Goods")
    protected List<Goods> goods;
    @XmlElement(name = "ITU")
    protected List<ITU> itu;
    @XmlElement(name = "RollingRoadUnit")
    protected List<RollingRoadUnit> rollingRoadUnit;

    /**
     * Gets the value of the wagonNumberFreight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWagonNumberFreight() {
        return wagonNumberFreight;
    }

    /**
     * Sets the value of the wagonNumberFreight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWagonNumberFreight(String value) {
        this.wagonNumberFreight = value;
    }

    /**
     * Gets the value of the wagonDetails property.
     * 
     * @return
     *     possible object is
     *     {@link Wagons.WagonDetails }
     *     
     */
    public Wagons.WagonDetails getWagonDetails() {
        return wagonDetails;
    }

    /**
     * Sets the value of the wagonDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Wagons.WagonDetails }
     *     
     */
    public void setWagonDetails(Wagons.WagonDetails value) {
        this.wagonDetails = value;
    }

    /**
     * Gets the value of the summaryOFGoodsWithSameRID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the summaryOFGoodsWithSameRID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSummaryOFGoodsWithSameRID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SummaryOFGoodsWithSameRID }
     * 
     * 
     */
    public List<SummaryOFGoodsWithSameRID> getSummaryOFGoodsWithSameRID() {
        if (summaryOFGoodsWithSameRID == null) {
            summaryOFGoodsWithSameRID = new ArrayList<SummaryOFGoodsWithSameRID>();
        }
        return this.summaryOFGoodsWithSameRID;
    }

    /**
     * Gets the value of the loadingTackles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the loadingTackles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLoadingTackles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LoadingTackles }
     * 
     * 
     */
    public List<LoadingTackles> getLoadingTackles() {
        if (loadingTackles == null) {
            loadingTackles = new ArrayList<LoadingTackles>();
        }
        return this.loadingTackles;
    }

    /**
     * Gets the value of the goods property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goods property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoods().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Goods }
     * 
     * 
     */
    public List<Goods> getGoods() {
        if (goods == null) {
            goods = new ArrayList<Goods>();
        }
        return this.goods;
    }

    /**
     * Gets the value of the itu property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the itu property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getITU().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ITU }
     * 
     * 
     */
    public List<ITU> getITU() {
        if (itu == null) {
            itu = new ArrayList<ITU>();
        }
        return this.itu;
    }

    /**
     * Gets the value of the rollingRoadUnit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rollingRoadUnit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRollingRoadUnit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RollingRoadUnit }
     * 
     * 
     */
    public List<RollingRoadUnit> getRollingRoadUnit() {
        if (rollingRoadUnit == null) {
            rollingRoadUnit = new ArrayList<RollingRoadUnit>();
        }
        return this.rollingRoadUnit;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://taf-jsg.info/schemes}LoadingStatus"/>
     *         &lt;element name="WagonInfo" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;maxLength value="500"/>
     *               &lt;minLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="WagonTypeDetails" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://taf-jsg.info/schemes}WagonWeightEmpty"/>
     *                   &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberOfAxles"/>
     *                   &lt;element ref="{http://taf-jsg.info/schemes}WagonLength"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element ref="{http://taf-jsg.info/schemes}TotalWeight" minOccurs="0"/>
     *         &lt;element name="LoadLimit" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;minInclusive value="0"/>
     *               &lt;totalDigits value="4"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{http://taf-jsg.info/schemes}Seals" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}Ship" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}DeliveryReference" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}OriginCountry" minOccurs="0"/>
     *         &lt;element name="ExceptionalConsignment" maxOccurs="10" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://taf-jsg.info/schemes}IM_Partner"/>
     *                   &lt;element name="PermissionNumber">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="24"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="ShuntingModalLabel" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *               &lt;enumeration value="13"/>
     *               &lt;enumeration value="15"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element ref="{http://taf-jsg.info/schemes}ReferenceNumbers" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "loadingStatus",
        "wagonInfo",
        "wagonTypeDetails",
        "totalWeight",
        "loadLimit",
        "seals",
        "ship",
        "deliveryReference",
        "originCountry",
        "exceptionalConsignment",
        "shuntingModalLabel",
        "referenceNumbers"
    })
    public static class WagonDetails {

        @XmlElement(name = "LoadingStatus", required = true)
        protected BigInteger loadingStatus;
        @XmlElement(name = "WagonInfo")
        protected String wagonInfo;
        @XmlElement(name = "WagonTypeDetails")
        protected Wagons.WagonDetails.WagonTypeDetails wagonTypeDetails;
        @XmlElement(name = "TotalWeight")
        protected Integer totalWeight;
        @XmlElement(name = "LoadLimit")
        protected BigDecimal loadLimit;
        @XmlElement(name = "Seals")
        protected Seals seals;
        @XmlElement(name = "Ship")
        protected Ship ship;
        @XmlElement(name = "DeliveryReference")
        protected String deliveryReference;
        @XmlElement(name = "OriginCountry")
        protected String originCountry;
        @XmlElement(name = "ExceptionalConsignment")
        protected List<Wagons.WagonDetails.ExceptionalConsignment> exceptionalConsignment;
        @XmlElement(name = "ShuntingModalLabel")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String shuntingModalLabel;
        @XmlElement(name = "ReferenceNumbers")
        protected ReferenceNumbers referenceNumbers;

        /**
         * Gets the value of the loadingStatus property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getLoadingStatus() {
            return loadingStatus;
        }

        /**
         * Sets the value of the loadingStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setLoadingStatus(BigInteger value) {
            this.loadingStatus = value;
        }

        /**
         * Gets the value of the wagonInfo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWagonInfo() {
            return wagonInfo;
        }

        /**
         * Sets the value of the wagonInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWagonInfo(String value) {
            this.wagonInfo = value;
        }

        /**
         * Gets the value of the wagonTypeDetails property.
         * 
         * @return
         *     possible object is
         *     {@link Wagons.WagonDetails.WagonTypeDetails }
         *     
         */
        public Wagons.WagonDetails.WagonTypeDetails getWagonTypeDetails() {
            return wagonTypeDetails;
        }

        /**
         * Sets the value of the wagonTypeDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link Wagons.WagonDetails.WagonTypeDetails }
         *     
         */
        public void setWagonTypeDetails(Wagons.WagonDetails.WagonTypeDetails value) {
            this.wagonTypeDetails = value;
        }

        /**
         * Gets the value of the totalWeight property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getTotalWeight() {
            return totalWeight;
        }

        /**
         * Sets the value of the totalWeight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setTotalWeight(Integer value) {
            this.totalWeight = value;
        }

        /**
         * Gets the value of the loadLimit property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLoadLimit() {
            return loadLimit;
        }

        /**
         * Sets the value of the loadLimit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLoadLimit(BigDecimal value) {
            this.loadLimit = value;
        }

        /**
         * Describes the seals used for the consignment
         * 										
         * 
         * @return
         *     possible object is
         *     {@link Seals }
         *     
         */
        public Seals getSeals() {
            return seals;
        }

        /**
         * Sets the value of the seals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Seals }
         *     
         */
        public void setSeals(Seals value) {
            this.seals = value;
        }

        /**
         * Additional information for transports, which
         * 											shall be handed over to a ship.
         * 										
         * 
         * @return
         *     possible object is
         *     {@link Ship }
         *     
         */
        public Ship getShip() {
            return ship;
        }

        /**
         * Sets the value of the ship property.
         * 
         * @param value
         *     allowed object is
         *     {@link Ship }
         *     
         */
        public void setShip(Ship value) {
            this.ship = value;
        }

        /**
         * Gets the value of the deliveryReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeliveryReference() {
            return deliveryReference;
        }

        /**
         * Sets the value of the deliveryReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeliveryReference(String value) {
            this.deliveryReference = value;
        }

        /**
         * Gets the value of the originCountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOriginCountry() {
            return originCountry;
        }

        /**
         * Sets the value of the originCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOriginCountry(String value) {
            this.originCountry = value;
        }

        /**
         * Gets the value of the exceptionalConsignment property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the exceptionalConsignment property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExceptionalConsignment().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Wagons.WagonDetails.ExceptionalConsignment }
         * 
         * 
         */
        public List<Wagons.WagonDetails.ExceptionalConsignment> getExceptionalConsignment() {
            if (exceptionalConsignment == null) {
                exceptionalConsignment = new ArrayList<Wagons.WagonDetails.ExceptionalConsignment>();
            }
            return this.exceptionalConsignment;
        }

        /**
         * Gets the value of the shuntingModalLabel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShuntingModalLabel() {
            return shuntingModalLabel;
        }

        /**
         * Sets the value of the shuntingModalLabel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShuntingModalLabel(String value) {
            this.shuntingModalLabel = value;
        }

        /**
         * Gets the value of the referenceNumbers property.
         * 
         * @return
         *     possible object is
         *     {@link ReferenceNumbers }
         *     
         */
        public ReferenceNumbers getReferenceNumbers() {
            return referenceNumbers;
        }

        /**
         * Sets the value of the referenceNumbers property.
         * 
         * @param value
         *     allowed object is
         *     {@link ReferenceNumbers }
         *     
         */
        public void setReferenceNumbers(ReferenceNumbers value) {
            this.referenceNumbers = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://taf-jsg.info/schemes}IM_Partner"/>
         *         &lt;element name="PermissionNumber">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="24"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "imPartner",
            "permissionNumber"
        })
        public static class ExceptionalConsignment {

            @XmlElement(name = "IM_Partner")
            protected int imPartner;
            @XmlElement(name = "PermissionNumber", required = true)
            protected String permissionNumber;

            /**
             * Gets the value of the imPartner property.
             * 
             */
            public int getIMPartner() {
                return imPartner;
            }

            /**
             * Sets the value of the imPartner property.
             * 
             */
            public void setIMPartner(int value) {
                this.imPartner = value;
            }

            /**
             * Gets the value of the permissionNumber property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPermissionNumber() {
                return permissionNumber;
            }

            /**
             * Sets the value of the permissionNumber property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPermissionNumber(String value) {
                this.permissionNumber = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://taf-jsg.info/schemes}WagonWeightEmpty"/>
         *         &lt;element ref="{http://taf-jsg.info/schemes}WagonNumberOfAxles"/>
         *         &lt;element ref="{http://taf-jsg.info/schemes}WagonLength"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "wagonWeightEmpty",
            "wagonNumberOfAxles",
            "wagonLength"
        })
        public static class WagonTypeDetails {

            @XmlElement(name = "WagonWeightEmpty")
            protected int wagonWeightEmpty;
            @XmlElement(name = "WagonNumberOfAxles")
            protected int wagonNumberOfAxles;
            @XmlElement(name = "WagonLength")
            protected int wagonLength;

            /**
             * Gets the value of the wagonWeightEmpty property.
             * 
             */
            public int getWagonWeightEmpty() {
                return wagonWeightEmpty;
            }

            /**
             * Sets the value of the wagonWeightEmpty property.
             * 
             */
            public void setWagonWeightEmpty(int value) {
                this.wagonWeightEmpty = value;
            }

            /**
             * Gets the value of the wagonNumberOfAxles property.
             * 
             */
            public int getWagonNumberOfAxles() {
                return wagonNumberOfAxles;
            }

            /**
             * Sets the value of the wagonNumberOfAxles property.
             * 
             */
            public void setWagonNumberOfAxles(int value) {
                this.wagonNumberOfAxles = value;
            }

            /**
             * Gets the value of the wagonLength property.
             * 
             */
            public int getWagonLength() {
                return wagonLength;
            }

            /**
             * Sets the value of the wagonLength property.
             * 
             */
            public void setWagonLength(int value) {
                this.wagonLength = value;
            }

        }

    }

}
