//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.22 at 09:30:01 PM CEST 
//


package info.taf_jsg.schemes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConsignmentLevelData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}Customer" maxOccurs="2"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}ConsignmentNumber"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}Goods"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}AgreedTimeOfDelivery"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}Destination"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}WagonInformation"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}ContractNumber" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}DangerousGoodsIndication" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}SpecialTreatments" minOccurs="0"/>
 *                   &lt;element name="PreviousWagonNumber" type="{http://taf-jsg.info/schemes}WagonIdent" minOccurs="0"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}PreviousConsignmentNumber" minOccurs="0"/>
 *                   &lt;sequence minOccurs="0">
 *                     &lt;element ref="{http://taf-jsg.info/schemes}NextIntermediateDestination"/>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}PreviousResponsibleRU"/>
 *                     &lt;element ref="{http://taf-jsg.info/schemes}NextResponsibleRU"/>
 *                   &lt;/sequence>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EventLevelData">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}WagonEventInformation"/>
 *                   &lt;element ref="{http://taf-jsg.info/schemes}VesselIndication" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://taf-jsg.info/schemes}RollingStockDataset"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "consignmentLevelData",
    "eventLevelData",
    "rollingStockDataset"
})
@XmlRootElement(name = "WIMO_Dataset")
public class WIMODataset {

    @XmlElement(name = "ConsignmentLevelData", required = true)
    protected WIMODataset.ConsignmentLevelData consignmentLevelData;
    @XmlElement(name = "EventLevelData", required = true)
    protected WIMODataset.EventLevelData eventLevelData;
    @XmlElement(name = "RollingStockDataset", required = true)
    protected RollingStockDataset rollingStockDataset;

    /**
     * Gets the value of the consignmentLevelData property.
     * 
     * @return
     *     possible object is
     *     {@link WIMODataset.ConsignmentLevelData }
     *     
     */
    public WIMODataset.ConsignmentLevelData getConsignmentLevelData() {
        return consignmentLevelData;
    }

    /**
     * Sets the value of the consignmentLevelData property.
     * 
     * @param value
     *     allowed object is
     *     {@link WIMODataset.ConsignmentLevelData }
     *     
     */
    public void setConsignmentLevelData(WIMODataset.ConsignmentLevelData value) {
        this.consignmentLevelData = value;
    }

    /**
     * Gets the value of the eventLevelData property.
     * 
     * @return
     *     possible object is
     *     {@link WIMODataset.EventLevelData }
     *     
     */
    public WIMODataset.EventLevelData getEventLevelData() {
        return eventLevelData;
    }

    /**
     * Sets the value of the eventLevelData property.
     * 
     * @param value
     *     allowed object is
     *     {@link WIMODataset.EventLevelData }
     *     
     */
    public void setEventLevelData(WIMODataset.EventLevelData value) {
        this.eventLevelData = value;
    }

    /**
     * Gets the value of the rollingStockDataset property.
     * 
     * @return
     *     possible object is
     *     {@link RollingStockDataset }
     *     
     */
    public RollingStockDataset getRollingStockDataset() {
        return rollingStockDataset;
    }

    /**
     * Sets the value of the rollingStockDataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link RollingStockDataset }
     *     
     */
    public void setRollingStockDataset(RollingStockDataset value) {
        this.rollingStockDataset = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://taf-jsg.info/schemes}Customer" maxOccurs="2"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}ConsignmentNumber"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}Goods"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}AgreedTimeOfDelivery"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}Destination"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}WagonInformation"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}ContractNumber" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}DangerousGoodsIndication" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}SpecialTreatments" minOccurs="0"/>
     *         &lt;element name="PreviousWagonNumber" type="{http://taf-jsg.info/schemes}WagonIdent" minOccurs="0"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}PreviousConsignmentNumber" minOccurs="0"/>
     *         &lt;sequence minOccurs="0">
     *           &lt;element ref="{http://taf-jsg.info/schemes}NextIntermediateDestination"/>
     *           &lt;element ref="{http://taf-jsg.info/schemes}PreviousResponsibleRU"/>
     *           &lt;element ref="{http://taf-jsg.info/schemes}NextResponsibleRU"/>
     *         &lt;/sequence>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customer",
        "consignmentNumber",
        "goods",
        "agreedTimeOfDelivery",
        "destination",
        "wagonInformation",
        "contractNumber",
        "dangerousGoodsIndication",
        "specialTreatments",
        "previousWagonNumber",
        "previousConsignmentNumber",
        "nextIntermediateDestination",
        "previousResponsibleRU",
        "nextResponsibleRU"
    })
    public static class ConsignmentLevelData {

        @XmlElement(name = "Customer", required = true)
        protected List<Customer> customer;
        @XmlElement(name = "ConsignmentNumber", required = true)
        protected ConsignmentIdent consignmentNumber;
        @XmlElement(name = "Goods", required = true)
        protected Goods goods;
        @XmlElement(name = "AgreedTimeOfDelivery", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar agreedTimeOfDelivery;
        @XmlElement(name = "Destination", required = true)
        protected LocationIdent destination;
        @XmlElement(name = "WagonInformation", required = true)
        protected WagonInformation wagonInformation;
        @XmlElement(name = "ContractNumber")
        protected String contractNumber;
        @XmlElement(name = "DangerousGoodsIndication")
        protected DanGoodsType dangerousGoodsIndication;
        @XmlElement(name = "SpecialTreatments")
        protected SpecialTreatments specialTreatments;
        @XmlElement(name = "PreviousWagonNumber")
        protected String previousWagonNumber;
        @XmlElement(name = "PreviousConsignmentNumber")
        protected ConsignmentIdent previousConsignmentNumber;
        @XmlElement(name = "NextIntermediateDestination")
        protected NextIntermediateDestination nextIntermediateDestination;
        @XmlElement(name = "PreviousResponsibleRU")
        protected Integer previousResponsibleRU;
        @XmlElement(name = "NextResponsibleRU")
        protected Integer nextResponsibleRU;

        /**
         * Gets the value of the customer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Customer }
         * 
         * 
         */
        public List<Customer> getCustomer() {
            if (customer == null) {
                customer = new ArrayList<Customer>();
            }
            return this.customer;
        }

        /**
         * Gets the value of the consignmentNumber property.
         * 
         * @return
         *     possible object is
         *     {@link ConsignmentIdent }
         *     
         */
        public ConsignmentIdent getConsignmentNumber() {
            return consignmentNumber;
        }

        /**
         * Sets the value of the consignmentNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConsignmentIdent }
         *     
         */
        public void setConsignmentNumber(ConsignmentIdent value) {
            this.consignmentNumber = value;
        }

        /**
         * Gets the value of the goods property.
         * 
         * @return
         *     possible object is
         *     {@link Goods }
         *     
         */
        public Goods getGoods() {
            return goods;
        }

        /**
         * Sets the value of the goods property.
         * 
         * @param value
         *     allowed object is
         *     {@link Goods }
         *     
         */
        public void setGoods(Goods value) {
            this.goods = value;
        }

        /**
         * Gets the value of the agreedTimeOfDelivery property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getAgreedTimeOfDelivery() {
            return agreedTimeOfDelivery;
        }

        /**
         * Sets the value of the agreedTimeOfDelivery property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setAgreedTimeOfDelivery(XMLGregorianCalendar value) {
            this.agreedTimeOfDelivery = value;
        }

        /**
         * Gets the value of the destination property.
         * 
         * @return
         *     possible object is
         *     {@link LocationIdent }
         *     
         */
        public LocationIdent getDestination() {
            return destination;
        }

        /**
         * Sets the value of the destination property.
         * 
         * @param value
         *     allowed object is
         *     {@link LocationIdent }
         *     
         */
        public void setDestination(LocationIdent value) {
            this.destination = value;
        }

        /**
         * Gets the value of the wagonInformation property.
         * 
         * @return
         *     possible object is
         *     {@link WagonInformation }
         *     
         */
        public WagonInformation getWagonInformation() {
            return wagonInformation;
        }

        /**
         * Sets the value of the wagonInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link WagonInformation }
         *     
         */
        public void setWagonInformation(WagonInformation value) {
            this.wagonInformation = value;
        }

        /**
         * Gets the value of the contractNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractNumber() {
            return contractNumber;
        }

        /**
         * Sets the value of the contractNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractNumber(String value) {
            this.contractNumber = value;
        }

        /**
         * Gets the value of the dangerousGoodsIndication property.
         * 
         * @return
         *     possible object is
         *     {@link DanGoodsType }
         *     
         */
        public DanGoodsType getDangerousGoodsIndication() {
            return dangerousGoodsIndication;
        }

        /**
         * Sets the value of the dangerousGoodsIndication property.
         * 
         * @param value
         *     allowed object is
         *     {@link DanGoodsType }
         *     
         */
        public void setDangerousGoodsIndication(DanGoodsType value) {
            this.dangerousGoodsIndication = value;
        }

        /**
         * Gets the value of the specialTreatments property.
         * 
         * @return
         *     possible object is
         *     {@link SpecialTreatments }
         *     
         */
        public SpecialTreatments getSpecialTreatments() {
            return specialTreatments;
        }

        /**
         * Sets the value of the specialTreatments property.
         * 
         * @param value
         *     allowed object is
         *     {@link SpecialTreatments }
         *     
         */
        public void setSpecialTreatments(SpecialTreatments value) {
            this.specialTreatments = value;
        }

        /**
         * Gets the value of the previousWagonNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPreviousWagonNumber() {
            return previousWagonNumber;
        }

        /**
         * Sets the value of the previousWagonNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPreviousWagonNumber(String value) {
            this.previousWagonNumber = value;
        }

        /**
         * Gets the value of the previousConsignmentNumber property.
         * 
         * @return
         *     possible object is
         *     {@link ConsignmentIdent }
         *     
         */
        public ConsignmentIdent getPreviousConsignmentNumber() {
            return previousConsignmentNumber;
        }

        /**
         * Sets the value of the previousConsignmentNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link ConsignmentIdent }
         *     
         */
        public void setPreviousConsignmentNumber(ConsignmentIdent value) {
            this.previousConsignmentNumber = value;
        }

        /**
         * Gets the value of the nextIntermediateDestination property.
         * 
         * @return
         *     possible object is
         *     {@link NextIntermediateDestination }
         *     
         */
        public NextIntermediateDestination getNextIntermediateDestination() {
            return nextIntermediateDestination;
        }

        /**
         * Sets the value of the nextIntermediateDestination property.
         * 
         * @param value
         *     allowed object is
         *     {@link NextIntermediateDestination }
         *     
         */
        public void setNextIntermediateDestination(NextIntermediateDestination value) {
            this.nextIntermediateDestination = value;
        }

        /**
         * Gets the value of the previousResponsibleRU property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getPreviousResponsibleRU() {
            return previousResponsibleRU;
        }

        /**
         * Sets the value of the previousResponsibleRU property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPreviousResponsibleRU(Integer value) {
            this.previousResponsibleRU = value;
        }

        /**
         * Gets the value of the nextResponsibleRU property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getNextResponsibleRU() {
            return nextResponsibleRU;
        }

        /**
         * Sets the value of the nextResponsibleRU property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setNextResponsibleRU(Integer value) {
            this.nextResponsibleRU = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://taf-jsg.info/schemes}WagonEventInformation"/>
     *         &lt;element ref="{http://taf-jsg.info/schemes}VesselIndication" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "wagonEventInformation",
        "vesselIndication"
    })
    public static class EventLevelData {

        @XmlElement(name = "WagonEventInformation", required = true)
        protected WagonEventInformation wagonEventInformation;
        @XmlElement(name = "VesselIndication")
        protected VesselIndication vesselIndication;

        /**
         * Gets the value of the wagonEventInformation property.
         * 
         * @return
         *     possible object is
         *     {@link WagonEventInformation }
         *     
         */
        public WagonEventInformation getWagonEventInformation() {
            return wagonEventInformation;
        }

        /**
         * Sets the value of the wagonEventInformation property.
         * 
         * @param value
         *     allowed object is
         *     {@link WagonEventInformation }
         *     
         */
        public void setWagonEventInformation(WagonEventInformation value) {
            this.wagonEventInformation = value;
        }

        /**
         * Gets the value of the vesselIndication property.
         * 
         * @return
         *     possible object is
         *     {@link VesselIndication }
         *     
         */
        public VesselIndication getVesselIndication() {
            return vesselIndication;
        }

        /**
         * Sets the value of the vesselIndication property.
         * 
         * @param value
         *     allowed object is
         *     {@link VesselIndication }
         *     
         */
        public void setVesselIndication(VesselIndication value) {
            this.vesselIndication = value;
        }

    }

}
